-- ============================================================================
-- GENERATED FILE — do not edit by hand.
--
--   bun run db:seed:generate
--
-- Source of truth: src/types/facility-staff.ts (PERMISSION_GROUPS, ROLE_PRESETS).
-- Editing this file directly guarantees it will be silently overwritten and
-- that the database will disagree with the UI about who can do what.
--
-- 168 permission keys across 19 groups
-- 930 role-preset grants across 13 roles
-- ============================================================================

insert into public.permissions (key, category, is_personal, description) values
  ('view_dashboard', 'core', true, 'View dashboard'),
  ('view_own_schedule', 'core', true, 'View own schedule'),
  ('view_team_schedule', 'core', true, 'View team schedule'),
  ('view_own_documents', 'core', true, 'View own documents'),
  ('view_onboarding', 'core', true, 'View onboarding material'),
  ('view_training_materials', 'core', true, 'View training material'),
  ('manage_own_tasks', 'core', true, 'Manage own tasks'),
  ('view_own_profile', 'core', true, 'View own profile'),
  ('edit_own_profile', 'core', true, 'Edit own profile'),
  ('clock_in_out', 'core', true, 'Clock in / out'),
  ('request_time_off', 'core', true, 'Request time off'),
  ('request_shift_swap', 'core', true, 'Request a shift swap'),
  ('submit_availability', 'core', true, 'Submit availability'),
  ('view_own_performance', 'core', true, 'View own performance'),
  ('view_own_writeups', 'core', true, 'View own write-ups'),
  ('message_manager', 'core', true, 'Message manager'),
  ('view_client_list', 'clients', false, 'View client list'),
  ('view_clients', 'clients', false, 'View client profiles'),
  ('view_client_contact_info', 'clients', false, 'View contact info'),
  ('view_client_address', 'clients', false, 'View home address'),
  ('view_client_financial', 'clients', false, 'View client financials'),
  ('create_clients', 'clients', false, 'Create clients'),
  ('edit_clients', 'clients', false, 'Edit clients'),
  ('delete_clients', 'clients', false, 'Delete clients'),
  ('merge_clients', 'clients', false, 'Merge duplicate clients'),
  ('export_clients', 'clients', false, 'Export client data'),
  ('view_pet_records', 'clients', false, 'View pet records'),
  ('edit_pet_records', 'clients', false, 'Edit pet records'),
  ('add_pet_notes', 'clients', false, 'Add pet notes'),
  ('view_pet_medical', 'clients', false, 'View pet medical records'),
  ('edit_pet_medical', 'clients', false, 'Edit pet medical records'),
  ('view_client_documents', 'clients', false, 'View client documents'),
  ('view_bookings', 'bookings', false, 'View bookings'),
  ('view_occupancy_calendar', 'bookings', false, 'View occupancy calendar'),
  ('view_estimates', 'bookings', false, 'View estimates'),
  ('view_evaluations', 'bookings', false, 'View evaluations'),
  ('create_bookings', 'bookings', false, 'Create bookings'),
  ('edit_bookings', 'bookings', false, 'Edit bookings'),
  ('cancel_bookings', 'bookings', false, 'Cancel bookings'),
  ('reschedule_bookings', 'bookings', false, 'Reschedule bookings'),
  ('view_booking_financials', 'bookings', false, 'View booking amounts'),
  ('view_all_calendars', 'bookings', false, 'View all calendars'),
  ('manage_booking_calendar', 'bookings', false, 'Manage booking calendar'),
  ('manage_waitlist', 'bookings', false, 'Manage waitlist'),
  ('override_booking_capacity', 'bookings', false, 'Override capacity limits'),
  ('view_grooming_queue', 'grooming', false, 'View grooming queue'),
  ('grooming_view_own_calendar', 'grooming', false, 'View own grooming calendar'),
  ('grooming_view_all_calendars', 'grooming', false, 'View all grooming calendars'),
  ('perform_grooming', 'grooming', false, 'Perform grooming'),
  ('add_grooming_notes', 'grooming', false, 'Add grooming notes'),
  ('grooming_upload_photos', 'grooming', false, 'Upload grooming photos'),
  ('grooming_manage_styles', 'grooming', false, 'Manage grooming styles'),
  ('grooming_edit_pricing', 'grooming', false, 'Edit grooming pricing'),
  ('boarding_view_dashboard', 'boarding', false, 'View boarding dashboard'),
  ('boarding_daily_care_log', 'boarding', false, 'Boarding daily care log'),
  ('boarding_assign_kennels', 'boarding', false, 'Assign kennels'),
  ('boarding_log_feeding', 'boarding', false, 'Log boarding feeding'),
  ('boarding_log_medication', 'boarding', false, 'Log boarding medication'),
  ('boarding_manage_belongings', 'boarding', false, 'Manage pet belongings'),
  ('boarding_send_updates', 'boarding', false, 'Send boarding updates'),
  ('daycare_view_dashboard', 'daycare', false, 'View daycare dashboard'),
  ('daycare_check_in_out', 'daycare', false, 'Daycare check in / out'),
  ('daycare_log_activity', 'daycare', false, 'Log daycare activity'),
  ('daycare_manage_groups', 'daycare', false, 'Manage playgroups'),
  ('daycare_incident_report', 'daycare', false, 'File daycare incident report'),
  ('daycare_send_updates', 'daycare', false, 'Send daycare updates'),
  ('view_training_queue', 'training', false, 'View training queue'),
  ('training_view_own_calendar', 'training', false, 'View own training calendar'),
  ('run_training_sessions', 'training', false, 'Run training sessions'),
  ('add_training_notes', 'training', false, 'Add training notes'),
  ('training_manage_programs', 'training', false, 'Manage training programs'),
  ('training_log_progress', 'training', false, 'Log training progress'),
  ('training_issue_certificates', 'training', false, 'Issue certificates'),
  ('retail_pos_access', 'retail', false, 'Access point of sale'),
  ('retail_process_sale', 'retail', false, 'Process a sale'),
  ('retail_process_return', 'retail', false, 'Process a return'),
  ('retail_apply_discount', 'retail', false, 'Apply retail discount'),
  ('retail_manage_inventory', 'retail', false, 'Manage retail inventory'),
  ('retail_manage_products', 'retail', false, 'Manage products'),
  ('retail_manage_suppliers', 'retail', false, 'Manage suppliers'),
  ('retail_view_reports', 'retail', false, 'View retail reports'),
  ('scheduling_view_all', 'staff_scheduling', false, 'View all staff schedules'),
  ('scheduling_create_shifts', 'staff_scheduling', false, 'Create shifts'),
  ('scheduling_edit_shifts', 'staff_scheduling', false, 'Edit shifts'),
  ('scheduling_publish', 'staff_scheduling', false, 'Publish schedules'),
  ('scheduling_approve_time_off', 'staff_scheduling', false, 'Approve time-off requests'),
  ('scheduling_approve_swaps', 'staff_scheduling', false, 'Approve shift swaps'),
  ('scheduling_manage_availability', 'staff_scheduling', false, 'Manage availability'),
  ('scheduling_view_labor_cost', 'staff_scheduling', false, 'View labor cost'),
  ('calling_view', 'calling_messages', false, 'View calling'),
  ('calling_make_calls', 'calling_messages', false, 'Make calls'),
  ('calling_view_recordings', 'calling_messages', false, 'View call recordings'),
  ('calling_view_voicemail', 'calling_messages', false, 'View voicemail'),
  ('calling_manage_routing', 'calling_messages', false, 'Manage call routing'),
  ('messages_view_inbox', 'calling_messages', false, 'View message inbox'),
  ('messages_send', 'calling_messages', false, 'Send messages'),
  ('messages_view_all_threads', 'calling_messages', false, 'View all message threads'),
  ('messages_manage_templates', 'calling_messages', false, 'Manage message templates'),
  ('view_services', 'services_pricing', false, 'View services'),
  ('manage_services', 'services_pricing', false, 'Manage services'),
  ('manage_rates', 'services_pricing', false, 'Manage rates & prices'),
  ('take_payment', 'finance', false, 'Take payment'),
  ('financial_take_payment', 'finance', false, 'Take payment (POS/booking)'),
  ('process_refund', 'finance', false, 'Process refunds'),
  ('apply_discount', 'finance', false, 'Apply discounts'),
  ('financial_view_amounts', 'finance', false, 'View financial amounts'),
  ('financial_view_revenue', 'finance', false, 'View revenue'),
  ('view_revenue', 'finance', false, 'View revenue (legacy)'),
  ('financial_reports', 'finance', false, 'View financial reports'),
  ('view_financial_reports', 'finance', false, 'View financial reports (legacy)'),
  ('export_financials', 'finance', false, 'Export financials'),
  ('financial_manage_invoices', 'finance', false, 'Manage invoices'),
  ('financial_manage_gift_cards', 'finance', false, 'Manage gift cards'),
  ('financial_manage_payouts', 'finance', false, 'Manage payouts'),
  ('financial_view_labor_cost', 'finance', false, 'View labor cost'),
  ('open_close_register', 'finance', false, 'Open / close cash register'),
  ('marketing_view', 'marketing', false, 'View marketing'),
  ('marketing_create_campaigns', 'marketing', false, 'Create campaigns'),
  ('marketing_manage_automations', 'marketing', false, 'Manage automations'),
  ('marketing_view_analytics', 'marketing', false, 'View campaign analytics'),
  ('marketing_manage_reviews', 'marketing', false, 'Manage reviews'),
  ('marketing_manage_loyalty', 'marketing', false, 'Manage loyalty program'),
  ('marketing_manage_referrals', 'marketing', false, 'Manage referrals'),
  ('check_in_out', 'operations', false, 'Check in / out'),
  ('log_feedings', 'operations', false, 'Log feedings'),
  ('log_medications', 'operations', false, 'Log medications'),
  ('log_potty_breaks', 'operations', false, 'Log potty breaks'),
  ('log_play_sessions', 'operations', false, 'Log play sessions'),
  ('log_incidents', 'operations', false, 'Log incidents'),
  ('log_cleaning', 'operations', false, 'Log cleaning'),
  ('ops_incidents_view', 'operations', false, 'View incidents'),
  ('ops_incidents_manage', 'operations', false, 'Manage incidents'),
  ('ops_smart_insights', 'operations', false, 'View Smart Insights'),
  ('ops_view_reports', 'operations', false, 'View operations reports'),
  ('ops_manage_tasks', 'operations', false, 'Manage team tasks'),
  ('ops_manage_checklists', 'operations', false, 'Manage checklists'),
  ('view_petcams', 'operations', false, 'View live pet cams'),
  ('view_staff', 'staff', false, 'View staff directory'),
  ('view_staff_permissions', 'staff', false, 'View staff permissions'),
  ('manage_staff', 'staff', false, 'Manage staff'),
  ('manage_roles', 'staff', false, 'Manage roles & permissions'),
  ('view_payroll', 'staff', false, 'View payroll'),
  ('edit_payroll', 'staff', false, 'Edit payroll'),
  ('manage_onboarding', 'staff', false, 'Manage onboarding checklists'),
  ('manage_writeups', 'staff', false, 'Manage write-ups'),
  ('view_staff_performance', 'staff', false, 'View staff performance'),
  ('view_inventory', 'inventory', false, 'View inventory'),
  ('manage_supplies', 'inventory', false, 'Manage supplies'),
  ('communicate_clients', 'comms', false, 'Message clients'),
  ('send_marketing', 'comms', false, 'Send marketing campaigns'),
  ('manage_facility_settings', 'facility', false, 'Facility settings'),
  ('manage_locations', 'facility', false, 'Manage locations'),
  ('manage_integrations', 'facility', false, 'Manage integrations'),
  ('settings_general', 'facility', false, 'General settings'),
  ('settings_subscription', 'facility', false, 'Manage subscription'),
  ('settings_billing', 'facility', false, 'Manage billing'),
  ('settings_manage_forms', 'facility', false, 'Manage forms'),
  ('view_waivers', 'facility', false, 'View digital waivers'),
  ('view_intake_forms', 'facility', false, 'View intake forms'),
  ('settings_manage_notifications', 'facility', false, 'Manage notification settings'),
  ('settings_manage_taxes', 'facility', false, 'Manage taxes'),
  ('settings_audit_log', 'facility', false, 'View audit log'),
  ('settings_data_export', 'facility', false, 'Export facility data'),
  ('hq_view', 'hq', false, 'View HQ'),
  ('hq_manage_locations', 'hq', false, 'Manage HQ locations'),
  ('hq_view_consolidated_reports', 'hq', false, 'View consolidated reports'),
  ('hq_transfer_resources', 'hq', false, 'Transfer resources'),
  ('hq_manage_settings', 'hq', false, 'Manage HQ settings')
on conflict (key) do update
  set category    = excluded.category,
      is_personal = excluded.is_personal,
      description = excluded.description;

-- Anything the TypeScript no longer declares should not survive here. The
-- cascade on permission_key clears dependent grants at all three layers.
delete from public.permissions
 where key not in ('view_dashboard', 'view_own_schedule', 'view_team_schedule', 'view_own_documents', 'view_onboarding', 'view_training_materials', 'manage_own_tasks', 'view_own_profile', 'edit_own_profile', 'clock_in_out', 'request_time_off', 'request_shift_swap', 'submit_availability', 'view_own_performance', 'view_own_writeups', 'message_manager', 'view_client_list', 'view_clients', 'view_client_contact_info', 'view_client_address', 'view_client_financial', 'create_clients', 'edit_clients', 'delete_clients', 'merge_clients', 'export_clients', 'view_pet_records', 'edit_pet_records', 'add_pet_notes', 'view_pet_medical', 'edit_pet_medical', 'view_client_documents', 'view_bookings', 'view_occupancy_calendar', 'view_estimates', 'view_evaluations', 'create_bookings', 'edit_bookings', 'cancel_bookings', 'reschedule_bookings', 'view_booking_financials', 'view_all_calendars', 'manage_booking_calendar', 'manage_waitlist', 'override_booking_capacity', 'view_grooming_queue', 'grooming_view_own_calendar', 'grooming_view_all_calendars', 'perform_grooming', 'add_grooming_notes', 'grooming_upload_photos', 'grooming_manage_styles', 'grooming_edit_pricing', 'boarding_view_dashboard', 'boarding_daily_care_log', 'boarding_assign_kennels', 'boarding_log_feeding', 'boarding_log_medication', 'boarding_manage_belongings', 'boarding_send_updates', 'daycare_view_dashboard', 'daycare_check_in_out', 'daycare_log_activity', 'daycare_manage_groups', 'daycare_incident_report', 'daycare_send_updates', 'view_training_queue', 'training_view_own_calendar', 'run_training_sessions', 'add_training_notes', 'training_manage_programs', 'training_log_progress', 'training_issue_certificates', 'retail_pos_access', 'retail_process_sale', 'retail_process_return', 'retail_apply_discount', 'retail_manage_inventory', 'retail_manage_products', 'retail_manage_suppliers', 'retail_view_reports', 'scheduling_view_all', 'scheduling_create_shifts', 'scheduling_edit_shifts', 'scheduling_publish', 'scheduling_approve_time_off', 'scheduling_approve_swaps', 'scheduling_manage_availability', 'scheduling_view_labor_cost', 'calling_view', 'calling_make_calls', 'calling_view_recordings', 'calling_view_voicemail', 'calling_manage_routing', 'messages_view_inbox', 'messages_send', 'messages_view_all_threads', 'messages_manage_templates', 'view_services', 'manage_services', 'manage_rates', 'take_payment', 'financial_take_payment', 'process_refund', 'apply_discount', 'financial_view_amounts', 'financial_view_revenue', 'view_revenue', 'financial_reports', 'view_financial_reports', 'export_financials', 'financial_manage_invoices', 'financial_manage_gift_cards', 'financial_manage_payouts', 'financial_view_labor_cost', 'open_close_register', 'marketing_view', 'marketing_create_campaigns', 'marketing_manage_automations', 'marketing_view_analytics', 'marketing_manage_reviews', 'marketing_manage_loyalty', 'marketing_manage_referrals', 'check_in_out', 'log_feedings', 'log_medications', 'log_potty_breaks', 'log_play_sessions', 'log_incidents', 'log_cleaning', 'ops_incidents_view', 'ops_incidents_manage', 'ops_smart_insights', 'ops_view_reports', 'ops_manage_tasks', 'ops_manage_checklists', 'view_petcams', 'view_staff', 'view_staff_permissions', 'manage_staff', 'manage_roles', 'view_payroll', 'edit_payroll', 'manage_onboarding', 'manage_writeups', 'view_staff_performance', 'view_inventory', 'manage_supplies', 'communicate_clients', 'send_marketing', 'manage_facility_settings', 'manage_locations', 'manage_integrations', 'settings_general', 'settings_subscription', 'settings_billing', 'settings_manage_forms', 'view_waivers', 'view_intake_forms', 'settings_manage_notifications', 'settings_manage_taxes', 'settings_audit_log', 'settings_data_export', 'hq_view', 'hq_manage_locations', 'hq_view_consolidated_reports', 'hq_transfer_resources', 'hq_manage_settings');

insert into public.role_preset_permissions (role, permission_key, scope) values
  ('owner', 'view_dashboard', 'anytime'),
  ('owner', 'view_own_schedule', 'anytime'),
  ('owner', 'view_team_schedule', 'anytime'),
  ('owner', 'view_own_documents', 'anytime'),
  ('owner', 'view_onboarding', 'anytime'),
  ('owner', 'view_training_materials', 'anytime'),
  ('owner', 'manage_own_tasks', 'anytime'),
  ('owner', 'view_own_profile', 'anytime'),
  ('owner', 'edit_own_profile', 'anytime'),
  ('owner', 'clock_in_out', 'anytime'),
  ('owner', 'request_time_off', 'anytime'),
  ('owner', 'request_shift_swap', 'anytime'),
  ('owner', 'submit_availability', 'anytime'),
  ('owner', 'view_own_performance', 'anytime'),
  ('owner', 'view_own_writeups', 'anytime'),
  ('owner', 'message_manager', 'anytime'),
  ('owner', 'view_client_list', 'anytime'),
  ('owner', 'view_clients', 'anytime'),
  ('owner', 'view_client_contact_info', 'anytime'),
  ('owner', 'view_client_address', 'anytime'),
  ('owner', 'view_client_financial', 'anytime'),
  ('owner', 'create_clients', 'anytime'),
  ('owner', 'edit_clients', 'anytime'),
  ('owner', 'delete_clients', 'anytime'),
  ('owner', 'merge_clients', 'anytime'),
  ('owner', 'export_clients', 'anytime'),
  ('owner', 'view_pet_records', 'anytime'),
  ('owner', 'edit_pet_records', 'anytime'),
  ('owner', 'add_pet_notes', 'anytime'),
  ('owner', 'view_pet_medical', 'anytime'),
  ('owner', 'edit_pet_medical', 'anytime'),
  ('owner', 'view_client_documents', 'anytime'),
  ('owner', 'view_bookings', 'anytime'),
  ('owner', 'view_occupancy_calendar', 'anytime'),
  ('owner', 'view_estimates', 'anytime'),
  ('owner', 'view_evaluations', 'anytime'),
  ('owner', 'create_bookings', 'anytime'),
  ('owner', 'edit_bookings', 'anytime'),
  ('owner', 'cancel_bookings', 'anytime'),
  ('owner', 'reschedule_bookings', 'anytime'),
  ('owner', 'view_booking_financials', 'anytime'),
  ('owner', 'view_all_calendars', 'anytime'),
  ('owner', 'manage_booking_calendar', 'anytime'),
  ('owner', 'manage_waitlist', 'anytime'),
  ('owner', 'override_booking_capacity', 'anytime'),
  ('owner', 'view_grooming_queue', 'anytime'),
  ('owner', 'grooming_view_own_calendar', 'anytime'),
  ('owner', 'grooming_view_all_calendars', 'anytime'),
  ('owner', 'perform_grooming', 'anytime'),
  ('owner', 'add_grooming_notes', 'anytime'),
  ('owner', 'grooming_upload_photos', 'anytime'),
  ('owner', 'grooming_manage_styles', 'anytime'),
  ('owner', 'grooming_edit_pricing', 'anytime'),
  ('owner', 'boarding_view_dashboard', 'anytime'),
  ('owner', 'boarding_daily_care_log', 'anytime'),
  ('owner', 'boarding_assign_kennels', 'anytime'),
  ('owner', 'boarding_log_feeding', 'anytime'),
  ('owner', 'boarding_log_medication', 'anytime'),
  ('owner', 'boarding_manage_belongings', 'anytime'),
  ('owner', 'boarding_send_updates', 'anytime'),
  ('owner', 'daycare_view_dashboard', 'anytime'),
  ('owner', 'daycare_check_in_out', 'anytime'),
  ('owner', 'daycare_log_activity', 'anytime'),
  ('owner', 'daycare_manage_groups', 'anytime'),
  ('owner', 'daycare_incident_report', 'anytime'),
  ('owner', 'daycare_send_updates', 'anytime'),
  ('owner', 'view_training_queue', 'anytime'),
  ('owner', 'training_view_own_calendar', 'anytime'),
  ('owner', 'run_training_sessions', 'anytime'),
  ('owner', 'add_training_notes', 'anytime'),
  ('owner', 'training_manage_programs', 'anytime'),
  ('owner', 'training_log_progress', 'anytime'),
  ('owner', 'training_issue_certificates', 'anytime'),
  ('owner', 'retail_pos_access', 'anytime'),
  ('owner', 'retail_process_sale', 'anytime'),
  ('owner', 'retail_process_return', 'anytime'),
  ('owner', 'retail_apply_discount', 'anytime'),
  ('owner', 'retail_manage_inventory', 'anytime'),
  ('owner', 'retail_manage_products', 'anytime'),
  ('owner', 'retail_manage_suppliers', 'anytime'),
  ('owner', 'retail_view_reports', 'anytime'),
  ('owner', 'scheduling_view_all', 'anytime'),
  ('owner', 'scheduling_create_shifts', 'anytime'),
  ('owner', 'scheduling_edit_shifts', 'anytime'),
  ('owner', 'scheduling_publish', 'anytime'),
  ('owner', 'scheduling_approve_time_off', 'anytime'),
  ('owner', 'scheduling_approve_swaps', 'anytime'),
  ('owner', 'scheduling_manage_availability', 'anytime'),
  ('owner', 'scheduling_view_labor_cost', 'anytime'),
  ('owner', 'calling_view', 'anytime'),
  ('owner', 'calling_make_calls', 'anytime'),
  ('owner', 'calling_view_recordings', 'anytime'),
  ('owner', 'calling_view_voicemail', 'anytime'),
  ('owner', 'calling_manage_routing', 'anytime'),
  ('owner', 'messages_view_inbox', 'anytime'),
  ('owner', 'messages_send', 'anytime'),
  ('owner', 'messages_view_all_threads', 'anytime'),
  ('owner', 'messages_manage_templates', 'anytime'),
  ('owner', 'view_services', 'anytime'),
  ('owner', 'manage_services', 'anytime'),
  ('owner', 'manage_rates', 'anytime'),
  ('owner', 'take_payment', 'anytime'),
  ('owner', 'financial_take_payment', 'anytime'),
  ('owner', 'process_refund', 'anytime'),
  ('owner', 'apply_discount', 'anytime'),
  ('owner', 'financial_view_amounts', 'anytime'),
  ('owner', 'financial_view_revenue', 'anytime'),
  ('owner', 'view_revenue', 'anytime'),
  ('owner', 'financial_reports', 'anytime'),
  ('owner', 'view_financial_reports', 'anytime'),
  ('owner', 'export_financials', 'anytime'),
  ('owner', 'financial_manage_invoices', 'anytime'),
  ('owner', 'financial_manage_gift_cards', 'anytime'),
  ('owner', 'financial_manage_payouts', 'anytime'),
  ('owner', 'financial_view_labor_cost', 'anytime'),
  ('owner', 'open_close_register', 'anytime'),
  ('owner', 'marketing_view', 'anytime'),
  ('owner', 'marketing_create_campaigns', 'anytime'),
  ('owner', 'marketing_manage_automations', 'anytime'),
  ('owner', 'marketing_view_analytics', 'anytime'),
  ('owner', 'marketing_manage_reviews', 'anytime'),
  ('owner', 'marketing_manage_loyalty', 'anytime'),
  ('owner', 'marketing_manage_referrals', 'anytime'),
  ('owner', 'check_in_out', 'anytime'),
  ('owner', 'log_feedings', 'anytime'),
  ('owner', 'log_medications', 'anytime'),
  ('owner', 'log_potty_breaks', 'anytime'),
  ('owner', 'log_play_sessions', 'anytime'),
  ('owner', 'log_incidents', 'anytime'),
  ('owner', 'log_cleaning', 'anytime'),
  ('owner', 'ops_incidents_view', 'anytime'),
  ('owner', 'ops_incidents_manage', 'anytime'),
  ('owner', 'ops_smart_insights', 'anytime'),
  ('owner', 'ops_view_reports', 'anytime'),
  ('owner', 'ops_manage_tasks', 'anytime'),
  ('owner', 'ops_manage_checklists', 'anytime'),
  ('owner', 'view_petcams', 'anytime'),
  ('owner', 'view_staff', 'anytime'),
  ('owner', 'view_staff_permissions', 'anytime'),
  ('owner', 'manage_staff', 'anytime'),
  ('owner', 'manage_roles', 'anytime'),
  ('owner', 'view_payroll', 'anytime'),
  ('owner', 'edit_payroll', 'anytime'),
  ('owner', 'manage_onboarding', 'anytime'),
  ('owner', 'manage_writeups', 'anytime'),
  ('owner', 'view_staff_performance', 'anytime'),
  ('owner', 'view_inventory', 'anytime'),
  ('owner', 'manage_supplies', 'anytime'),
  ('owner', 'communicate_clients', 'anytime'),
  ('owner', 'send_marketing', 'anytime'),
  ('owner', 'manage_facility_settings', 'anytime'),
  ('owner', 'manage_locations', 'anytime'),
  ('owner', 'manage_integrations', 'anytime'),
  ('owner', 'settings_general', 'anytime'),
  ('owner', 'settings_subscription', 'anytime'),
  ('owner', 'settings_billing', 'anytime'),
  ('owner', 'settings_manage_forms', 'anytime'),
  ('owner', 'view_waivers', 'anytime'),
  ('owner', 'view_intake_forms', 'anytime'),
  ('owner', 'settings_manage_notifications', 'anytime'),
  ('owner', 'settings_manage_taxes', 'anytime'),
  ('owner', 'settings_audit_log', 'anytime'),
  ('owner', 'settings_data_export', 'anytime'),
  ('owner', 'hq_view', 'anytime'),
  ('owner', 'hq_manage_locations', 'anytime'),
  ('owner', 'hq_view_consolidated_reports', 'anytime'),
  ('owner', 'hq_transfer_resources', 'anytime'),
  ('owner', 'hq_manage_settings', 'anytime'),
  ('admin', 'view_dashboard', 'anytime'),
  ('admin', 'view_own_schedule', 'anytime'),
  ('admin', 'view_team_schedule', 'anytime'),
  ('admin', 'view_own_documents', 'anytime'),
  ('admin', 'view_onboarding', 'anytime'),
  ('admin', 'view_training_materials', 'anytime'),
  ('admin', 'manage_own_tasks', 'anytime'),
  ('admin', 'view_own_profile', 'anytime'),
  ('admin', 'edit_own_profile', 'anytime'),
  ('admin', 'clock_in_out', 'anytime'),
  ('admin', 'request_time_off', 'anytime'),
  ('admin', 'request_shift_swap', 'anytime'),
  ('admin', 'submit_availability', 'anytime'),
  ('admin', 'view_own_performance', 'anytime'),
  ('admin', 'view_own_writeups', 'anytime'),
  ('admin', 'message_manager', 'anytime'),
  ('admin', 'view_client_list', 'anytime'),
  ('admin', 'view_clients', 'anytime'),
  ('admin', 'view_client_contact_info', 'anytime'),
  ('admin', 'view_client_address', 'anytime'),
  ('admin', 'view_client_financial', 'anytime'),
  ('admin', 'create_clients', 'anytime'),
  ('admin', 'edit_clients', 'anytime'),
  ('admin', 'delete_clients', 'anytime'),
  ('admin', 'merge_clients', 'anytime'),
  ('admin', 'export_clients', 'anytime'),
  ('admin', 'view_pet_records', 'anytime'),
  ('admin', 'edit_pet_records', 'anytime'),
  ('admin', 'add_pet_notes', 'anytime'),
  ('admin', 'view_pet_medical', 'anytime'),
  ('admin', 'edit_pet_medical', 'anytime'),
  ('admin', 'view_client_documents', 'anytime'),
  ('admin', 'view_bookings', 'anytime'),
  ('admin', 'view_occupancy_calendar', 'anytime'),
  ('admin', 'view_estimates', 'anytime'),
  ('admin', 'view_evaluations', 'anytime'),
  ('admin', 'create_bookings', 'anytime'),
  ('admin', 'edit_bookings', 'anytime'),
  ('admin', 'cancel_bookings', 'anytime'),
  ('admin', 'reschedule_bookings', 'anytime'),
  ('admin', 'view_booking_financials', 'anytime'),
  ('admin', 'view_all_calendars', 'anytime'),
  ('admin', 'manage_booking_calendar', 'anytime'),
  ('admin', 'manage_waitlist', 'anytime'),
  ('admin', 'override_booking_capacity', 'anytime'),
  ('admin', 'view_grooming_queue', 'anytime'),
  ('admin', 'grooming_view_own_calendar', 'anytime'),
  ('admin', 'grooming_view_all_calendars', 'anytime'),
  ('admin', 'perform_grooming', 'anytime'),
  ('admin', 'add_grooming_notes', 'anytime'),
  ('admin', 'grooming_upload_photos', 'anytime'),
  ('admin', 'grooming_manage_styles', 'anytime'),
  ('admin', 'grooming_edit_pricing', 'anytime'),
  ('admin', 'boarding_view_dashboard', 'anytime'),
  ('admin', 'boarding_daily_care_log', 'anytime'),
  ('admin', 'boarding_assign_kennels', 'anytime'),
  ('admin', 'boarding_log_feeding', 'anytime'),
  ('admin', 'boarding_log_medication', 'anytime'),
  ('admin', 'boarding_manage_belongings', 'anytime'),
  ('admin', 'boarding_send_updates', 'anytime'),
  ('admin', 'daycare_view_dashboard', 'anytime'),
  ('admin', 'daycare_check_in_out', 'anytime'),
  ('admin', 'daycare_log_activity', 'anytime'),
  ('admin', 'daycare_manage_groups', 'anytime'),
  ('admin', 'daycare_incident_report', 'anytime'),
  ('admin', 'daycare_send_updates', 'anytime'),
  ('admin', 'view_training_queue', 'anytime'),
  ('admin', 'training_view_own_calendar', 'anytime'),
  ('admin', 'run_training_sessions', 'anytime'),
  ('admin', 'add_training_notes', 'anytime'),
  ('admin', 'training_manage_programs', 'anytime'),
  ('admin', 'training_log_progress', 'anytime'),
  ('admin', 'training_issue_certificates', 'anytime'),
  ('admin', 'retail_pos_access', 'anytime'),
  ('admin', 'retail_process_sale', 'anytime'),
  ('admin', 'retail_process_return', 'anytime'),
  ('admin', 'retail_apply_discount', 'anytime'),
  ('admin', 'retail_manage_inventory', 'anytime'),
  ('admin', 'retail_manage_products', 'anytime'),
  ('admin', 'retail_manage_suppliers', 'anytime'),
  ('admin', 'retail_view_reports', 'anytime'),
  ('admin', 'scheduling_view_all', 'anytime'),
  ('admin', 'scheduling_create_shifts', 'anytime'),
  ('admin', 'scheduling_edit_shifts', 'anytime'),
  ('admin', 'scheduling_publish', 'anytime'),
  ('admin', 'scheduling_approve_time_off', 'anytime'),
  ('admin', 'scheduling_approve_swaps', 'anytime'),
  ('admin', 'scheduling_manage_availability', 'anytime'),
  ('admin', 'scheduling_view_labor_cost', 'anytime'),
  ('admin', 'calling_view', 'anytime'),
  ('admin', 'calling_make_calls', 'anytime'),
  ('admin', 'calling_view_recordings', 'anytime'),
  ('admin', 'calling_view_voicemail', 'anytime'),
  ('admin', 'calling_manage_routing', 'anytime'),
  ('admin', 'messages_view_inbox', 'anytime'),
  ('admin', 'messages_send', 'anytime'),
  ('admin', 'messages_view_all_threads', 'anytime'),
  ('admin', 'messages_manage_templates', 'anytime'),
  ('admin', 'view_services', 'anytime'),
  ('admin', 'manage_services', 'anytime'),
  ('admin', 'manage_rates', 'anytime'),
  ('admin', 'take_payment', 'anytime'),
  ('admin', 'financial_take_payment', 'anytime'),
  ('admin', 'process_refund', 'anytime'),
  ('admin', 'apply_discount', 'anytime'),
  ('admin', 'financial_view_amounts', 'anytime'),
  ('admin', 'financial_view_revenue', 'anytime'),
  ('admin', 'view_revenue', 'anytime'),
  ('admin', 'financial_reports', 'anytime'),
  ('admin', 'view_financial_reports', 'anytime'),
  ('admin', 'export_financials', 'anytime'),
  ('admin', 'financial_manage_invoices', 'anytime'),
  ('admin', 'financial_manage_gift_cards', 'anytime'),
  ('admin', 'financial_manage_payouts', 'anytime'),
  ('admin', 'financial_view_labor_cost', 'anytime'),
  ('admin', 'open_close_register', 'anytime'),
  ('admin', 'marketing_view', 'anytime'),
  ('admin', 'marketing_create_campaigns', 'anytime'),
  ('admin', 'marketing_manage_automations', 'anytime'),
  ('admin', 'marketing_view_analytics', 'anytime'),
  ('admin', 'marketing_manage_reviews', 'anytime'),
  ('admin', 'marketing_manage_loyalty', 'anytime'),
  ('admin', 'marketing_manage_referrals', 'anytime'),
  ('admin', 'check_in_out', 'anytime'),
  ('admin', 'log_feedings', 'anytime'),
  ('admin', 'log_medications', 'anytime'),
  ('admin', 'log_potty_breaks', 'anytime'),
  ('admin', 'log_play_sessions', 'anytime'),
  ('admin', 'log_incidents', 'anytime'),
  ('admin', 'log_cleaning', 'anytime'),
  ('admin', 'ops_incidents_view', 'anytime'),
  ('admin', 'ops_incidents_manage', 'anytime'),
  ('admin', 'ops_smart_insights', 'anytime'),
  ('admin', 'ops_view_reports', 'anytime'),
  ('admin', 'ops_manage_tasks', 'anytime'),
  ('admin', 'ops_manage_checklists', 'anytime'),
  ('admin', 'view_petcams', 'anytime'),
  ('admin', 'view_staff', 'anytime'),
  ('admin', 'view_staff_permissions', 'anytime'),
  ('admin', 'manage_staff', 'anytime'),
  ('admin', 'manage_roles', 'anytime'),
  ('admin', 'view_payroll', 'anytime'),
  ('admin', 'edit_payroll', 'anytime'),
  ('admin', 'manage_onboarding', 'anytime'),
  ('admin', 'manage_writeups', 'anytime'),
  ('admin', 'view_staff_performance', 'anytime'),
  ('admin', 'view_inventory', 'anytime'),
  ('admin', 'manage_supplies', 'anytime'),
  ('admin', 'communicate_clients', 'anytime'),
  ('admin', 'send_marketing', 'anytime'),
  ('admin', 'manage_facility_settings', 'anytime'),
  ('admin', 'manage_locations', 'anytime'),
  ('admin', 'manage_integrations', 'anytime'),
  ('admin', 'settings_general', 'anytime'),
  ('admin', 'settings_subscription', 'anytime'),
  ('admin', 'settings_billing', 'anytime'),
  ('admin', 'settings_manage_forms', 'anytime'),
  ('admin', 'view_waivers', 'anytime'),
  ('admin', 'view_intake_forms', 'anytime'),
  ('admin', 'settings_manage_notifications', 'anytime'),
  ('admin', 'settings_manage_taxes', 'anytime'),
  ('admin', 'settings_audit_log', 'anytime'),
  ('admin', 'settings_data_export', 'anytime'),
  ('admin', 'hq_view', 'anytime'),
  ('admin', 'hq_manage_locations', 'anytime'),
  ('admin', 'hq_view_consolidated_reports', 'anytime'),
  ('admin', 'hq_transfer_resources', 'anytime'),
  ('admin', 'hq_manage_settings', 'anytime'),
  ('manager', 'view_dashboard', 'anytime'),
  ('manager', 'view_own_schedule', 'anytime'),
  ('manager', 'view_team_schedule', 'anytime'),
  ('manager', 'view_own_documents', 'anytime'),
  ('manager', 'view_onboarding', 'anytime'),
  ('manager', 'view_training_materials', 'anytime'),
  ('manager', 'manage_own_tasks', 'anytime'),
  ('manager', 'view_own_profile', 'anytime'),
  ('manager', 'edit_own_profile', 'anytime'),
  ('manager', 'clock_in_out', 'anytime'),
  ('manager', 'request_time_off', 'anytime'),
  ('manager', 'request_shift_swap', 'anytime'),
  ('manager', 'submit_availability', 'anytime'),
  ('manager', 'view_own_performance', 'anytime'),
  ('manager', 'view_own_writeups', 'anytime'),
  ('manager', 'message_manager', 'anytime'),
  ('manager', 'view_client_list', 'anytime'),
  ('manager', 'view_clients', 'anytime'),
  ('manager', 'view_client_contact_info', 'anytime'),
  ('manager', 'view_client_address', 'anytime'),
  ('manager', 'view_client_financial', 'anytime'),
  ('manager', 'create_clients', 'anytime'),
  ('manager', 'edit_clients', 'anytime'),
  ('manager', 'merge_clients', 'anytime'),
  ('manager', 'export_clients', 'anytime'),
  ('manager', 'view_pet_records', 'anytime'),
  ('manager', 'edit_pet_records', 'anytime'),
  ('manager', 'add_pet_notes', 'anytime'),
  ('manager', 'view_pet_medical', 'anytime'),
  ('manager', 'edit_pet_medical', 'anytime'),
  ('manager', 'view_client_documents', 'anytime'),
  ('manager', 'view_bookings', 'anytime'),
  ('manager', 'view_occupancy_calendar', 'anytime'),
  ('manager', 'view_estimates', 'anytime'),
  ('manager', 'view_evaluations', 'anytime'),
  ('manager', 'create_bookings', 'anytime'),
  ('manager', 'edit_bookings', 'anytime'),
  ('manager', 'cancel_bookings', 'anytime'),
  ('manager', 'reschedule_bookings', 'anytime'),
  ('manager', 'view_booking_financials', 'anytime'),
  ('manager', 'view_all_calendars', 'anytime'),
  ('manager', 'manage_booking_calendar', 'anytime'),
  ('manager', 'manage_waitlist', 'anytime'),
  ('manager', 'override_booking_capacity', 'anytime'),
  ('manager', 'view_grooming_queue', 'anytime'),
  ('manager', 'grooming_view_all_calendars', 'anytime'),
  ('manager', 'add_grooming_notes', 'anytime'),
  ('manager', 'grooming_upload_photos', 'anytime'),
  ('manager', 'grooming_manage_styles', 'anytime'),
  ('manager', 'boarding_view_dashboard', 'anytime'),
  ('manager', 'boarding_daily_care_log', 'anytime'),
  ('manager', 'boarding_assign_kennels', 'anytime'),
  ('manager', 'boarding_manage_belongings', 'anytime'),
  ('manager', 'boarding_send_updates', 'anytime'),
  ('manager', 'daycare_view_dashboard', 'anytime'),
  ('manager', 'daycare_manage_groups', 'anytime'),
  ('manager', 'daycare_incident_report', 'anytime'),
  ('manager', 'daycare_send_updates', 'anytime'),
  ('manager', 'view_training_queue', 'anytime'),
  ('manager', 'training_manage_programs', 'anytime'),
  ('manager', 'retail_pos_access', 'anytime'),
  ('manager', 'retail_process_sale', 'anytime'),
  ('manager', 'retail_process_return', 'anytime'),
  ('manager', 'retail_apply_discount', 'anytime'),
  ('manager', 'retail_manage_inventory', 'anytime'),
  ('manager', 'retail_manage_products', 'anytime'),
  ('manager', 'retail_manage_suppliers', 'anytime'),
  ('manager', 'retail_view_reports', 'anytime'),
  ('manager', 'scheduling_view_all', 'anytime'),
  ('manager', 'scheduling_create_shifts', 'anytime'),
  ('manager', 'scheduling_edit_shifts', 'anytime'),
  ('manager', 'scheduling_publish', 'anytime'),
  ('manager', 'scheduling_approve_time_off', 'anytime'),
  ('manager', 'scheduling_approve_swaps', 'anytime'),
  ('manager', 'scheduling_manage_availability', 'anytime'),
  ('manager', 'scheduling_view_labor_cost', 'anytime'),
  ('manager', 'calling_view', 'anytime'),
  ('manager', 'calling_make_calls', 'anytime'),
  ('manager', 'calling_view_recordings', 'anytime'),
  ('manager', 'calling_view_voicemail', 'anytime'),
  ('manager', 'calling_manage_routing', 'anytime'),
  ('manager', 'messages_view_inbox', 'anytime'),
  ('manager', 'messages_send', 'anytime'),
  ('manager', 'messages_view_all_threads', 'anytime'),
  ('manager', 'messages_manage_templates', 'anytime'),
  ('manager', 'view_services', 'anytime'),
  ('manager', 'manage_services', 'anytime'),
  ('manager', 'manage_rates', 'anytime'),
  ('manager', 'take_payment', 'anytime'),
  ('manager', 'financial_take_payment', 'anytime'),
  ('manager', 'process_refund', 'anytime'),
  ('manager', 'apply_discount', 'anytime'),
  ('manager', 'financial_view_amounts', 'anytime'),
  ('manager', 'financial_view_revenue', 'anytime'),
  ('manager', 'view_revenue', 'anytime'),
  ('manager', 'financial_reports', 'anytime'),
  ('manager', 'view_financial_reports', 'anytime'),
  ('manager', 'export_financials', 'anytime'),
  ('manager', 'financial_manage_invoices', 'anytime'),
  ('manager', 'financial_manage_gift_cards', 'anytime'),
  ('manager', 'financial_view_labor_cost', 'anytime'),
  ('manager', 'open_close_register', 'anytime'),
  ('manager', 'marketing_view', 'anytime'),
  ('manager', 'marketing_create_campaigns', 'anytime'),
  ('manager', 'marketing_manage_automations', 'anytime'),
  ('manager', 'marketing_view_analytics', 'anytime'),
  ('manager', 'marketing_manage_reviews', 'anytime'),
  ('manager', 'marketing_manage_loyalty', 'anytime'),
  ('manager', 'marketing_manage_referrals', 'anytime'),
  ('manager', 'check_in_out', 'anytime'),
  ('manager', 'log_feedings', 'anytime'),
  ('manager', 'log_medications', 'anytime'),
  ('manager', 'log_potty_breaks', 'anytime'),
  ('manager', 'log_play_sessions', 'anytime'),
  ('manager', 'log_incidents', 'anytime'),
  ('manager', 'log_cleaning', 'anytime'),
  ('manager', 'ops_incidents_view', 'anytime'),
  ('manager', 'ops_incidents_manage', 'anytime'),
  ('manager', 'ops_smart_insights', 'anytime'),
  ('manager', 'ops_view_reports', 'anytime'),
  ('manager', 'ops_manage_tasks', 'anytime'),
  ('manager', 'ops_manage_checklists', 'anytime'),
  ('manager', 'view_petcams', 'anytime'),
  ('manager', 'view_staff', 'anytime'),
  ('manager', 'view_staff_permissions', 'anytime'),
  ('manager', 'manage_staff', 'anytime'),
  ('manager', 'view_payroll', 'anytime'),
  ('manager', 'manage_onboarding', 'anytime'),
  ('manager', 'manage_writeups', 'anytime'),
  ('manager', 'view_staff_performance', 'anytime'),
  ('manager', 'view_inventory', 'anytime'),
  ('manager', 'manage_supplies', 'anytime'),
  ('manager', 'communicate_clients', 'anytime'),
  ('manager', 'send_marketing', 'anytime'),
  ('manager', 'settings_general', 'anytime'),
  ('manager', 'settings_manage_forms', 'anytime'),
  ('manager', 'view_waivers', 'anytime'),
  ('manager', 'view_intake_forms', 'anytime'),
  ('manager', 'settings_manage_notifications', 'anytime'),
  ('manager', 'hq_view', 'anytime'),
  ('manager', 'hq_view_consolidated_reports', 'anytime'),
  ('supervisor', 'view_dashboard', 'anytime'),
  ('supervisor', 'view_own_schedule', 'anytime'),
  ('supervisor', 'view_team_schedule', 'anytime'),
  ('supervisor', 'view_own_documents', 'anytime'),
  ('supervisor', 'view_onboarding', 'anytime'),
  ('supervisor', 'view_training_materials', 'anytime'),
  ('supervisor', 'manage_own_tasks', 'anytime'),
  ('supervisor', 'view_own_profile', 'anytime'),
  ('supervisor', 'edit_own_profile', 'anytime'),
  ('supervisor', 'clock_in_out', 'anytime'),
  ('supervisor', 'request_time_off', 'anytime'),
  ('supervisor', 'request_shift_swap', 'anytime'),
  ('supervisor', 'submit_availability', 'anytime'),
  ('supervisor', 'view_own_performance', 'anytime'),
  ('supervisor', 'view_own_writeups', 'anytime'),
  ('supervisor', 'message_manager', 'anytime'),
  ('supervisor', 'view_client_list', 'operating_hours'),
  ('supervisor', 'view_clients', 'operating_hours'),
  ('supervisor', 'view_client_contact_info', 'operating_hours'),
  ('supervisor', 'view_pet_records', 'operating_hours'),
  ('supervisor', 'edit_pet_records', 'operating_hours'),
  ('supervisor', 'add_pet_notes', 'operating_hours'),
  ('supervisor', 'view_pet_medical', 'operating_hours'),
  ('supervisor', 'view_client_documents', 'operating_hours'),
  ('supervisor', 'view_bookings', 'operating_hours'),
  ('supervisor', 'create_bookings', 'operating_hours'),
  ('supervisor', 'edit_bookings', 'operating_hours'),
  ('supervisor', 'cancel_bookings', 'operating_hours'),
  ('supervisor', 'reschedule_bookings', 'operating_hours'),
  ('supervisor', 'view_all_calendars', 'operating_hours'),
  ('supervisor', 'manage_booking_calendar', 'operating_hours'),
  ('supervisor', 'manage_waitlist', 'operating_hours'),
  ('supervisor', 'view_occupancy_calendar', 'operating_hours'),
  ('supervisor', 'view_estimates', 'operating_hours'),
  ('supervisor', 'view_evaluations', 'operating_hours'),
  ('supervisor', 'view_petcams', 'operating_hours'),
  ('supervisor', 'view_grooming_queue', 'operating_hours'),
  ('supervisor', 'grooming_view_all_calendars', 'operating_hours'),
  ('supervisor', 'boarding_view_dashboard', 'operating_hours'),
  ('supervisor', 'boarding_daily_care_log', 'operating_hours'),
  ('supervisor', 'daycare_view_dashboard', 'operating_hours'),
  ('supervisor', 'daycare_check_in_out', 'operating_hours'),
  ('supervisor', 'daycare_log_activity', 'operating_hours'),
  ('supervisor', 'daycare_manage_groups', 'operating_hours'),
  ('supervisor', 'daycare_incident_report', 'operating_hours'),
  ('supervisor', 'view_training_queue', 'operating_hours'),
  ('supervisor', 'retail_pos_access', 'operating_hours'),
  ('supervisor', 'retail_process_sale', 'operating_hours'),
  ('supervisor', 'retail_process_return', 'operating_hours'),
  ('supervisor', 'retail_apply_discount', 'operating_hours'),
  ('supervisor', 'view_booking_financials', 'operating_hours'),
  ('supervisor', 'financial_view_amounts', 'operating_hours'),
  ('supervisor', 'scheduling_view_all', 'operating_hours'),
  ('supervisor', 'scheduling_edit_shifts', 'operating_hours'),
  ('supervisor', 'scheduling_approve_time_off', 'operating_hours'),
  ('supervisor', 'scheduling_approve_swaps', 'operating_hours'),
  ('supervisor', 'scheduling_manage_availability', 'operating_hours'),
  ('supervisor', 'calling_view', 'operating_hours'),
  ('supervisor', 'calling_make_calls', 'operating_hours'),
  ('supervisor', 'messages_view_inbox', 'operating_hours'),
  ('supervisor', 'messages_send', 'operating_hours'),
  ('supervisor', 'take_payment', 'operating_hours'),
  ('supervisor', 'financial_take_payment', 'operating_hours'),
  ('supervisor', 'apply_discount', 'operating_hours'),
  ('supervisor', 'marketing_view', 'operating_hours'),
  ('supervisor', 'check_in_out', 'operating_hours'),
  ('supervisor', 'log_feedings', 'operating_hours'),
  ('supervisor', 'log_medications', 'operating_hours'),
  ('supervisor', 'log_potty_breaks', 'operating_hours'),
  ('supervisor', 'log_play_sessions', 'operating_hours'),
  ('supervisor', 'log_incidents', 'operating_hours'),
  ('supervisor', 'log_cleaning', 'operating_hours'),
  ('supervisor', 'ops_incidents_view', 'operating_hours'),
  ('supervisor', 'ops_incidents_manage', 'operating_hours'),
  ('supervisor', 'ops_view_reports', 'operating_hours'),
  ('supervisor', 'ops_manage_tasks', 'operating_hours'),
  ('supervisor', 'ops_manage_checklists', 'operating_hours'),
  ('supervisor', 'view_staff', 'operating_hours'),
  ('supervisor', 'view_staff_performance', 'operating_hours'),
  ('supervisor', 'view_inventory', 'operating_hours'),
  ('supervisor', 'manage_supplies', 'operating_hours'),
  ('supervisor', 'communicate_clients', 'operating_hours'),
  ('reception', 'view_dashboard', 'anytime'),
  ('reception', 'view_own_schedule', 'anytime'),
  ('reception', 'view_team_schedule', 'anytime'),
  ('reception', 'view_own_documents', 'anytime'),
  ('reception', 'view_onboarding', 'anytime'),
  ('reception', 'view_training_materials', 'anytime'),
  ('reception', 'manage_own_tasks', 'anytime'),
  ('reception', 'view_own_profile', 'anytime'),
  ('reception', 'edit_own_profile', 'anytime'),
  ('reception', 'clock_in_out', 'anytime'),
  ('reception', 'request_time_off', 'anytime'),
  ('reception', 'request_shift_swap', 'anytime'),
  ('reception', 'submit_availability', 'anytime'),
  ('reception', 'view_own_performance', 'anytime'),
  ('reception', 'view_own_writeups', 'anytime'),
  ('reception', 'message_manager', 'anytime'),
  ('reception', 'view_client_list', 'operating_hours'),
  ('reception', 'view_clients', 'operating_hours'),
  ('reception', 'view_client_contact_info', 'operating_hours'),
  ('reception', 'create_clients', 'operating_hours'),
  ('reception', 'edit_clients', 'operating_hours'),
  ('reception', 'view_pet_records', 'operating_hours'),
  ('reception', 'add_pet_notes', 'operating_hours'),
  ('reception', 'view_pet_medical', 'operating_hours'),
  ('reception', 'view_client_documents', 'operating_hours'),
  ('reception', 'view_bookings', 'operating_hours'),
  ('reception', 'create_bookings', 'operating_hours'),
  ('reception', 'edit_bookings', 'operating_hours'),
  ('reception', 'cancel_bookings', 'operating_hours'),
  ('reception', 'reschedule_bookings', 'operating_hours'),
  ('reception', 'view_booking_financials', 'operating_hours'),
  ('reception', 'view_all_calendars', 'operating_hours'),
  ('reception', 'manage_booking_calendar', 'operating_hours'),
  ('reception', 'manage_waitlist', 'operating_hours'),
  ('reception', 'view_occupancy_calendar', 'operating_hours'),
  ('reception', 'view_estimates', 'operating_hours'),
  ('reception', 'view_evaluations', 'operating_hours'),
  ('reception', 'view_petcams', 'operating_hours'),
  ('reception', 'view_grooming_queue', 'operating_hours'),
  ('reception', 'daycare_check_in_out', 'operating_hours'),
  ('reception', 'view_training_queue', 'operating_hours'),
  ('reception', 'retail_pos_access', 'operating_hours'),
  ('reception', 'retail_process_sale', 'operating_hours'),
  ('reception', 'retail_process_return', 'operating_hours'),
  ('reception', 'retail_apply_discount', 'operating_hours'),
  ('reception', 'calling_view', 'operating_hours'),
  ('reception', 'calling_make_calls', 'operating_hours'),
  ('reception', 'calling_view_voicemail', 'operating_hours'),
  ('reception', 'messages_view_inbox', 'operating_hours'),
  ('reception', 'messages_send', 'operating_hours'),
  ('reception', 'view_services', 'operating_hours'),
  ('reception', 'take_payment', 'operating_hours'),
  ('reception', 'financial_take_payment', 'operating_hours'),
  ('reception', 'apply_discount', 'operating_hours'),
  ('reception', 'financial_view_amounts', 'operating_hours'),
  ('reception', 'financial_manage_invoices', 'operating_hours'),
  ('reception', 'financial_manage_gift_cards', 'operating_hours'),
  ('reception', 'open_close_register', 'operating_hours'),
  ('reception', 'marketing_view', 'operating_hours'),
  ('reception', 'check_in_out', 'operating_hours'),
  ('reception', 'log_incidents', 'operating_hours'),
  ('reception', 'ops_incidents_view', 'operating_hours'),
  ('reception', 'ops_manage_tasks', 'operating_hours'),
  ('reception', 'view_inventory', 'operating_hours'),
  ('reception', 'communicate_clients', 'operating_hours'),
  ('groomer', 'view_dashboard', 'anytime'),
  ('groomer', 'view_own_schedule', 'anytime'),
  ('groomer', 'view_team_schedule', 'anytime'),
  ('groomer', 'view_own_documents', 'anytime'),
  ('groomer', 'view_onboarding', 'anytime'),
  ('groomer', 'view_training_materials', 'anytime'),
  ('groomer', 'manage_own_tasks', 'anytime'),
  ('groomer', 'view_own_profile', 'anytime'),
  ('groomer', 'edit_own_profile', 'anytime'),
  ('groomer', 'clock_in_out', 'anytime'),
  ('groomer', 'request_time_off', 'anytime'),
  ('groomer', 'request_shift_swap', 'anytime'),
  ('groomer', 'submit_availability', 'anytime'),
  ('groomer', 'view_own_performance', 'anytime'),
  ('groomer', 'view_own_writeups', 'anytime'),
  ('groomer', 'message_manager', 'anytime'),
  ('groomer', 'view_clients', 'assigned_shifts'),
  ('groomer', 'view_client_contact_info', 'assigned_shifts'),
  ('groomer', 'view_pet_records', 'assigned_shifts'),
  ('groomer', 'add_pet_notes', 'assigned_shifts'),
  ('groomer', 'view_pet_medical', 'assigned_shifts'),
  ('groomer', 'view_bookings', 'assigned_shifts'),
  ('groomer', 'view_all_calendars', 'assigned_shifts'),
  ('groomer', 'view_client_list', 'assigned_shifts'),
  ('groomer', 'view_grooming_queue', 'assigned_shifts'),
  ('groomer', 'grooming_view_own_calendar', 'assigned_shifts'),
  ('groomer', 'perform_grooming', 'assigned_shifts'),
  ('groomer', 'add_grooming_notes', 'assigned_shifts'),
  ('groomer', 'grooming_upload_photos', 'assigned_shifts'),
  ('groomer', 'check_in_out', 'assigned_shifts'),
  ('groomer', 'messages_view_inbox', 'assigned_shifts'),
  ('groomer', 'messages_send', 'assigned_shifts'),
  ('groomer', 'ops_manage_tasks', 'assigned_shifts'),
  ('groomer', 'log_incidents', 'assigned_shifts'),
  ('groomer', 'ops_incidents_view', 'assigned_shifts'),
  ('groomer', 'view_client_documents', 'assigned_shifts'),
  ('trainer', 'view_dashboard', 'anytime'),
  ('trainer', 'view_own_schedule', 'anytime'),
  ('trainer', 'view_team_schedule', 'anytime'),
  ('trainer', 'view_own_documents', 'anytime'),
  ('trainer', 'view_onboarding', 'anytime'),
  ('trainer', 'view_training_materials', 'anytime'),
  ('trainer', 'manage_own_tasks', 'anytime'),
  ('trainer', 'view_own_profile', 'anytime'),
  ('trainer', 'edit_own_profile', 'anytime'),
  ('trainer', 'clock_in_out', 'anytime'),
  ('trainer', 'request_time_off', 'anytime'),
  ('trainer', 'request_shift_swap', 'anytime'),
  ('trainer', 'submit_availability', 'anytime'),
  ('trainer', 'view_own_performance', 'anytime'),
  ('trainer', 'view_own_writeups', 'anytime'),
  ('trainer', 'message_manager', 'anytime'),
  ('trainer', 'view_clients', 'assigned_shifts'),
  ('trainer', 'view_client_contact_info', 'assigned_shifts'),
  ('trainer', 'view_pet_records', 'assigned_shifts'),
  ('trainer', 'add_pet_notes', 'assigned_shifts'),
  ('trainer', 'view_pet_medical', 'assigned_shifts'),
  ('trainer', 'view_bookings', 'assigned_shifts'),
  ('trainer', 'view_all_calendars', 'assigned_shifts'),
  ('trainer', 'view_client_list', 'assigned_shifts'),
  ('trainer', 'view_training_queue', 'assigned_shifts'),
  ('trainer', 'training_view_own_calendar', 'assigned_shifts'),
  ('trainer', 'run_training_sessions', 'assigned_shifts'),
  ('trainer', 'add_training_notes', 'assigned_shifts'),
  ('trainer', 'training_log_progress', 'assigned_shifts'),
  ('trainer', 'training_issue_certificates', 'assigned_shifts'),
  ('trainer', 'check_in_out', 'assigned_shifts'),
  ('trainer', 'messages_view_inbox', 'assigned_shifts'),
  ('trainer', 'messages_send', 'assigned_shifts'),
  ('trainer', 'ops_manage_tasks', 'assigned_shifts'),
  ('trainer', 'log_incidents', 'assigned_shifts'),
  ('trainer', 'ops_incidents_view', 'assigned_shifts'),
  ('trainer', 'view_client_documents', 'assigned_shifts'),
  ('caretaker', 'view_dashboard', 'anytime'),
  ('caretaker', 'view_own_schedule', 'anytime'),
  ('caretaker', 'view_team_schedule', 'anytime'),
  ('caretaker', 'view_own_documents', 'anytime'),
  ('caretaker', 'view_onboarding', 'anytime'),
  ('caretaker', 'view_training_materials', 'anytime'),
  ('caretaker', 'manage_own_tasks', 'anytime'),
  ('caretaker', 'view_own_profile', 'anytime'),
  ('caretaker', 'edit_own_profile', 'anytime'),
  ('caretaker', 'clock_in_out', 'anytime'),
  ('caretaker', 'request_time_off', 'anytime'),
  ('caretaker', 'request_shift_swap', 'anytime'),
  ('caretaker', 'submit_availability', 'anytime'),
  ('caretaker', 'view_own_performance', 'anytime'),
  ('caretaker', 'view_own_writeups', 'anytime'),
  ('caretaker', 'message_manager', 'anytime'),
  ('caretaker', 'view_pet_records', 'anytime'),
  ('caretaker', 'add_pet_notes', 'anytime'),
  ('caretaker', 'view_pet_medical', 'anytime'),
  ('caretaker', 'view_bookings', 'anytime'),
  ('caretaker', 'view_occupancy_calendar', 'anytime'),
  ('caretaker', 'view_client_list', 'anytime'),
  ('caretaker', 'messages_view_inbox', 'anytime'),
  ('caretaker', 'boarding_view_dashboard', 'anytime'),
  ('caretaker', 'boarding_daily_care_log', 'anytime'),
  ('caretaker', 'boarding_log_feeding', 'anytime'),
  ('caretaker', 'boarding_log_medication', 'anytime'),
  ('caretaker', 'boarding_manage_belongings', 'anytime'),
  ('caretaker', 'boarding_send_updates', 'anytime'),
  ('caretaker', 'daycare_view_dashboard', 'anytime'),
  ('caretaker', 'daycare_check_in_out', 'anytime'),
  ('caretaker', 'daycare_log_activity', 'anytime'),
  ('caretaker', 'daycare_incident_report', 'anytime'),
  ('caretaker', 'daycare_send_updates', 'anytime'),
  ('caretaker', 'check_in_out', 'anytime'),
  ('caretaker', 'log_feedings', 'anytime'),
  ('caretaker', 'log_medications', 'anytime'),
  ('caretaker', 'log_potty_breaks', 'anytime'),
  ('caretaker', 'log_play_sessions', 'anytime'),
  ('caretaker', 'log_incidents', 'anytime'),
  ('caretaker', 'log_cleaning', 'anytime'),
  ('caretaker', 'ops_manage_tasks', 'anytime'),
  ('caretaker', 'ops_incidents_view', 'anytime'),
  ('caretaker', 'view_clients', 'anytime'),
  ('caretaker', 'view_client_contact_info', 'anytime'),
  ('daycare_attendant', 'view_dashboard', 'anytime'),
  ('daycare_attendant', 'view_own_schedule', 'anytime'),
  ('daycare_attendant', 'view_team_schedule', 'anytime'),
  ('daycare_attendant', 'view_own_documents', 'anytime'),
  ('daycare_attendant', 'view_onboarding', 'anytime'),
  ('daycare_attendant', 'view_training_materials', 'anytime'),
  ('daycare_attendant', 'manage_own_tasks', 'anytime'),
  ('daycare_attendant', 'view_own_profile', 'anytime'),
  ('daycare_attendant', 'edit_own_profile', 'anytime'),
  ('daycare_attendant', 'clock_in_out', 'anytime'),
  ('daycare_attendant', 'request_time_off', 'anytime'),
  ('daycare_attendant', 'request_shift_swap', 'anytime'),
  ('daycare_attendant', 'submit_availability', 'anytime'),
  ('daycare_attendant', 'view_own_performance', 'anytime'),
  ('daycare_attendant', 'view_own_writeups', 'anytime'),
  ('daycare_attendant', 'message_manager', 'anytime'),
  ('daycare_attendant', 'view_pet_records', 'assigned_shifts'),
  ('daycare_attendant', 'add_pet_notes', 'assigned_shifts'),
  ('daycare_attendant', 'view_bookings', 'assigned_shifts'),
  ('daycare_attendant', 'boarding_daily_care_log', 'assigned_shifts'),
  ('daycare_attendant', 'view_occupancy_calendar', 'assigned_shifts'),
  ('daycare_attendant', 'view_client_list', 'assigned_shifts'),
  ('daycare_attendant', 'messages_view_inbox', 'assigned_shifts'),
  ('daycare_attendant', 'daycare_view_dashboard', 'assigned_shifts'),
  ('daycare_attendant', 'daycare_check_in_out', 'assigned_shifts'),
  ('daycare_attendant', 'daycare_log_activity', 'assigned_shifts'),
  ('daycare_attendant', 'daycare_manage_groups', 'assigned_shifts'),
  ('daycare_attendant', 'daycare_incident_report', 'assigned_shifts'),
  ('daycare_attendant', 'daycare_send_updates', 'assigned_shifts'),
  ('daycare_attendant', 'check_in_out', 'assigned_shifts'),
  ('daycare_attendant', 'log_feedings', 'assigned_shifts'),
  ('daycare_attendant', 'log_medications', 'assigned_shifts'),
  ('daycare_attendant', 'log_potty_breaks', 'assigned_shifts'),
  ('daycare_attendant', 'log_play_sessions', 'assigned_shifts'),
  ('daycare_attendant', 'log_incidents', 'assigned_shifts'),
  ('daycare_attendant', 'log_cleaning', 'assigned_shifts'),
  ('daycare_attendant', 'ops_manage_tasks', 'assigned_shifts'),
  ('daycare_attendant', 'ops_incidents_view', 'assigned_shifts'),
  ('daycare_attendant', 'view_pet_medical', 'assigned_shifts'),
  ('daycare_attendant', 'view_clients', 'assigned_shifts'),
  ('daycare_attendant', 'view_client_contact_info', 'assigned_shifts'),
  ('boarding_attendant', 'view_dashboard', 'anytime'),
  ('boarding_attendant', 'view_own_schedule', 'anytime'),
  ('boarding_attendant', 'view_team_schedule', 'anytime'),
  ('boarding_attendant', 'view_own_documents', 'anytime'),
  ('boarding_attendant', 'view_onboarding', 'anytime'),
  ('boarding_attendant', 'view_training_materials', 'anytime'),
  ('boarding_attendant', 'manage_own_tasks', 'anytime'),
  ('boarding_attendant', 'view_own_profile', 'anytime'),
  ('boarding_attendant', 'edit_own_profile', 'anytime'),
  ('boarding_attendant', 'clock_in_out', 'anytime'),
  ('boarding_attendant', 'request_time_off', 'anytime'),
  ('boarding_attendant', 'request_shift_swap', 'anytime'),
  ('boarding_attendant', 'submit_availability', 'anytime'),
  ('boarding_attendant', 'view_own_performance', 'anytime'),
  ('boarding_attendant', 'view_own_writeups', 'anytime'),
  ('boarding_attendant', 'message_manager', 'anytime'),
  ('boarding_attendant', 'view_pet_records', 'anytime'),
  ('boarding_attendant', 'add_pet_notes', 'anytime'),
  ('boarding_attendant', 'view_pet_medical', 'anytime'),
  ('boarding_attendant', 'view_bookings', 'anytime'),
  ('boarding_attendant', 'view_occupancy_calendar', 'anytime'),
  ('boarding_attendant', 'view_client_list', 'anytime'),
  ('boarding_attendant', 'messages_view_inbox', 'anytime'),
  ('boarding_attendant', 'boarding_view_dashboard', 'anytime'),
  ('boarding_attendant', 'boarding_daily_care_log', 'anytime'),
  ('boarding_attendant', 'boarding_assign_kennels', 'anytime'),
  ('boarding_attendant', 'boarding_log_feeding', 'anytime'),
  ('boarding_attendant', 'boarding_log_medication', 'anytime'),
  ('boarding_attendant', 'boarding_manage_belongings', 'anytime'),
  ('boarding_attendant', 'boarding_send_updates', 'anytime'),
  ('boarding_attendant', 'check_in_out', 'anytime'),
  ('boarding_attendant', 'log_feedings', 'anytime'),
  ('boarding_attendant', 'log_medications', 'anytime'),
  ('boarding_attendant', 'log_potty_breaks', 'anytime'),
  ('boarding_attendant', 'log_play_sessions', 'anytime'),
  ('boarding_attendant', 'log_incidents', 'anytime'),
  ('boarding_attendant', 'log_cleaning', 'anytime'),
  ('boarding_attendant', 'ops_manage_tasks', 'anytime'),
  ('boarding_attendant', 'ops_incidents_view', 'anytime'),
  ('boarding_attendant', 'view_clients', 'anytime'),
  ('boarding_attendant', 'view_client_contact_info', 'anytime'),
  ('retail', 'view_dashboard', 'anytime'),
  ('retail', 'view_own_schedule', 'anytime'),
  ('retail', 'view_team_schedule', 'anytime'),
  ('retail', 'view_own_documents', 'anytime'),
  ('retail', 'view_onboarding', 'anytime'),
  ('retail', 'view_training_materials', 'anytime'),
  ('retail', 'manage_own_tasks', 'anytime'),
  ('retail', 'view_own_profile', 'anytime'),
  ('retail', 'edit_own_profile', 'anytime'),
  ('retail', 'clock_in_out', 'anytime'),
  ('retail', 'request_time_off', 'anytime'),
  ('retail', 'request_shift_swap', 'anytime'),
  ('retail', 'submit_availability', 'anytime'),
  ('retail', 'view_own_performance', 'anytime'),
  ('retail', 'view_own_writeups', 'anytime'),
  ('retail', 'message_manager', 'anytime'),
  ('retail', 'view_client_list', 'operating_hours'),
  ('retail', 'view_clients', 'operating_hours'),
  ('retail', 'view_bookings', 'operating_hours'),
  ('retail', 'retail_pos_access', 'operating_hours'),
  ('retail', 'retail_process_sale', 'operating_hours'),
  ('retail', 'retail_process_return', 'operating_hours'),
  ('retail', 'retail_apply_discount', 'operating_hours'),
  ('retail', 'retail_manage_inventory', 'operating_hours'),
  ('retail', 'retail_manage_products', 'operating_hours'),
  ('retail', 'retail_manage_suppliers', 'operating_hours'),
  ('retail', 'retail_view_reports', 'operating_hours'),
  ('retail', 'take_payment', 'operating_hours'),
  ('retail', 'financial_take_payment', 'operating_hours'),
  ('retail', 'apply_discount', 'operating_hours'),
  ('retail', 'view_inventory', 'operating_hours'),
  ('retail', 'manage_supplies', 'operating_hours'),
  ('retail', 'messages_view_inbox', 'operating_hours'),
  ('retail', 'messages_send', 'operating_hours'),
  ('retail', 'ops_manage_tasks', 'operating_hours'),
  ('retail', 'financial_manage_gift_cards', 'operating_hours'),
  ('retail', 'financial_view_amounts', 'operating_hours'),
  ('retail', 'view_client_contact_info', 'operating_hours'),
  ('accountant', 'view_dashboard', 'anytime'),
  ('accountant', 'view_own_schedule', 'anytime'),
  ('accountant', 'view_team_schedule', 'anytime'),
  ('accountant', 'view_own_documents', 'anytime'),
  ('accountant', 'view_onboarding', 'anytime'),
  ('accountant', 'view_training_materials', 'anytime'),
  ('accountant', 'manage_own_tasks', 'anytime'),
  ('accountant', 'view_own_profile', 'anytime'),
  ('accountant', 'edit_own_profile', 'anytime'),
  ('accountant', 'clock_in_out', 'anytime'),
  ('accountant', 'request_time_off', 'anytime'),
  ('accountant', 'request_shift_swap', 'anytime'),
  ('accountant', 'submit_availability', 'anytime'),
  ('accountant', 'view_own_performance', 'anytime'),
  ('accountant', 'view_own_writeups', 'anytime'),
  ('accountant', 'message_manager', 'anytime'),
  ('accountant', 'view_client_list', 'anytime'),
  ('accountant', 'view_clients', 'anytime'),
  ('accountant', 'view_client_financial', 'anytime'),
  ('accountant', 'view_bookings', 'anytime'),
  ('accountant', 'view_booking_financials', 'anytime'),
  ('accountant', 'take_payment', 'anytime'),
  ('accountant', 'financial_take_payment', 'anytime'),
  ('accountant', 'process_refund', 'anytime'),
  ('accountant', 'apply_discount', 'anytime'),
  ('accountant', 'financial_view_amounts', 'anytime'),
  ('accountant', 'financial_view_revenue', 'anytime'),
  ('accountant', 'view_revenue', 'anytime'),
  ('accountant', 'financial_reports', 'anytime'),
  ('accountant', 'view_financial_reports', 'anytime'),
  ('accountant', 'export_financials', 'anytime'),
  ('accountant', 'financial_manage_invoices', 'anytime'),
  ('accountant', 'financial_manage_gift_cards', 'anytime'),
  ('accountant', 'financial_manage_payouts', 'anytime'),
  ('accountant', 'financial_view_labor_cost', 'anytime'),
  ('accountant', 'ops_view_reports', 'anytime'),
  ('accountant', 'scheduling_view_labor_cost', 'anytime'),
  ('accountant', 'view_payroll', 'anytime'),
  ('accountant', 'retail_view_reports', 'anytime'),
  ('accountant', 'marketing_view_analytics', 'anytime'),
  ('accountant', 'settings_billing', 'anytime'),
  ('accountant', 'settings_manage_taxes', 'anytime'),
  ('accountant', 'settings_data_export', 'anytime'),
  ('accountant', 'hq_view_consolidated_reports', 'anytime'),
  ('sanitation', 'view_dashboard', 'anytime'),
  ('sanitation', 'view_own_schedule', 'anytime'),
  ('sanitation', 'view_team_schedule', 'anytime'),
  ('sanitation', 'view_own_documents', 'anytime'),
  ('sanitation', 'view_onboarding', 'anytime'),
  ('sanitation', 'view_training_materials', 'anytime'),
  ('sanitation', 'manage_own_tasks', 'anytime'),
  ('sanitation', 'view_own_profile', 'anytime'),
  ('sanitation', 'edit_own_profile', 'anytime'),
  ('sanitation', 'clock_in_out', 'anytime'),
  ('sanitation', 'request_time_off', 'anytime'),
  ('sanitation', 'request_shift_swap', 'anytime'),
  ('sanitation', 'submit_availability', 'anytime'),
  ('sanitation', 'view_own_performance', 'anytime'),
  ('sanitation', 'view_own_writeups', 'anytime'),
  ('sanitation', 'message_manager', 'anytime'),
  ('sanitation', 'log_cleaning', 'assigned_shifts'),
  ('sanitation', 'check_in_out', 'assigned_shifts'),
  ('sanitation', 'view_inventory', 'assigned_shifts'),
  ('sanitation', 'manage_supplies', 'assigned_shifts'),
  ('sanitation', 'ops_manage_tasks', 'assigned_shifts'),
  ('sanitation', 'ops_manage_checklists', 'assigned_shifts'),
  ('sanitation', 'log_incidents', 'assigned_shifts'),
  ('sanitation', 'ops_incidents_view', 'assigned_shifts')
on conflict (role, permission_key) do update
  set scope = excluded.scope;

delete from public.role_preset_permissions rpp
 where not exists (
   select 1 from public.permissions p where p.key = rpp.permission_key
 );
