/**
 * Writes supabase/seed/facility-11-data.sql from the mock data in src/data.
 *
 * Run: bun run db:seed:operational
 *
 * A thin emitter over scripts/lib/operational-rows.ts — the mapping decisions
 * live there and are shared with the applier, so the file and the API path
 * cannot disagree about what a seeded row looks like.
 *
 * Prefer `bun run db:seed:apply` to actually load the data: it goes through
 * PostgREST as a signed-in user, so RLS is exercised on the way in. This file
 * is for review, for portability to an environment that has psql, and as the
 * thing you can read to see what the seed actually contains.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

import {
  buildSeedRows,
  reportAnomalies,
  DEMO_FACILITY_LEGACY_ID,
} from "./lib/operational-rows";

/**
 * The facility and location ids are resolved at RUN time by the SQL itself,
 * so these placeholders stand in while rows are built and are swapped for the
 * plpgsql variables on the way out. Hardcoding uuids here would break the
 * moment the seed ran against a different project.
 */
const FACILITY_PLACEHOLDER = "__FACILITY_ID__";
const LOCATION_PLACEHOLDER = "__LOCATION_ID__";
const DEMO_TIMEZONE = "America/Toronto";

const rows = buildSeedRows({
  facilityId: FACILITY_PLACEHOLDER,
  locationId: LOCATION_PLACEHOLDER,
  timeZone: DEMO_TIMEZONE,
});

function literal(value: unknown): string {
  if (value === null || value === undefined) return "null";
  if (value === FACILITY_PLACEHOLDER) return "v_facility_id";
  if (value === LOCATION_PLACEHOLDER) return "v_location_id";
  if (typeof value === "number")
    return Number.isFinite(value) ? String(value) : "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "object") {
    return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
  }
  return `'${String(value).replace(/'/g, "''")}'`;
}

const out: string[] = [];
const w = (line = "") => out.push(line);

w(
  "-- ============================================================================",
);
w(
  "-- Facility 11 operational data — GENERATED by scripts/generate-operational-seed.ts",
);
w("-- Do not edit by hand; edit the mocks in src/data and regenerate.");
w("--");
w(
  "-- Prefer `bun run db:seed:apply`, which loads the same rows through PostgREST",
);
w("-- as a signed-in user and therefore exercises RLS on the way in.");
w("--");
w("-- Idempotent: rows carry deterministic uuids and upsert.");
w(
  `-- Clients: ${rows.clients.length}  Pets: ${rows.pets.length}  Staff: ${rows.staff.length}  Bookings: ${rows.bookings.length}`,
);
if (rows.pulledIn.length) {
  w("--");
  w(
    "-- Pulled into the demo facility because their bookings are here, even though",
  );
  w("-- the mock data files them under another facility name:");
  for (const c of rows.pulledIn)
    w(`--   ${c.id} ${c.name} (mock facility: ${c.facility})`);
}
if (rows.remaps.length) {
  w("--");
  w("-- Pets re-referenced because the mock data reuses ids across owners:");
  for (const line of rows.remaps) w(`--   ${line}`);
}
w(
  "-- ============================================================================",
);
w();

/**
 * Sections rather than one statement: the booking `details` payloads make the
 * whole seed ~86KB, which is past what several SQL consoles accept, and a
 * failure names the stage it happened in.
 */
function section(name: string, emit: () => void) {
  w(`-- @section ${name}`);
  w("do $$");
  w("declare");
  w("  v_facility_id uuid;");
  w("  v_location_id uuid;");
  w("begin");
  w(
    `  select id into v_facility_id from public.facilities where legacy_id = '${DEMO_FACILITY_LEGACY_ID}';`,
  );
  w("  if v_facility_id is null then");
  w(
    "    raise exception 'Demo facility (legacy_id 11) not found. Run supabase/seed/dev-accounts.sql first.';",
  );
  w("  end if;");
  w(
    "  select id into v_location_id from public.locations where facility_id = v_facility_id and is_primary limit 1;",
  );
  w();
  emit();
  w("end $$;");
  w();
}

function insert(
  table: string,
  row: Record<string, unknown>,
  updateCols: string[],
) {
  const cols = Object.keys(row);
  w(`  insert into public.${table} (${cols.join(", ")})`);
  w(`  values (${cols.map((c) => literal(row[c])).join(", ")})`);
  w(`  on conflict (id) do update set`);
  w(`    ${updateCols.map((c) => `${c} = excluded.${c}`).join(", ")};`);
}

section("clients", () => {
  for (const row of rows.clients) {
    insert("clients", row, [
      "name",
      "email",
      "phone",
      "status",
      "address",
      "details",
    ]);
  }
});

section("pets", () => {
  for (const row of rows.pets) {
    insert("pets", row, ["name", "breed", "weight", "status", "details"]);
  }
});

section("staff", () => {
  for (const row of rows.staff) {
    insert("staff", row, [
      "first_name",
      "last_name",
      "email",
      "phone",
      "primary_role",
      "status",
      "details",
    ]);
  }
});

// Bookings in chunks — by far the largest section.
const PER_SECTION = 7;
for (let i = 0; i < rows.bookings.length; i += PER_SECTION) {
  const slice = rows.bookings.slice(i, i + PER_SECTION);
  section(`bookings-${i / PER_SECTION + 1}`, () => {
    for (const row of slice) {
      insert("bookings", row, [
        "status",
        "payment_status",
        "start_at",
        "end_at",
        "total_cost",
        "details",
      ]);
      const ids = rows.bookingPets.filter((bp) => bp.booking_id === row.id);
      for (const bp of ids) {
        w(
          `  insert into public.booking_pets (booking_id, pet_id) values (${literal(bp.booking_id)}, ${literal(bp.pet_id)}) on conflict do nothing;`,
        );
      }
    }
  });
}

section("sequences", () => {
  w(
    "  -- Advance the identity sequences past the explicit refs above, otherwise",
  );
  w("  -- the first row the app inserts collides with a seeded one.");
  w(
    "  perform setval(pg_get_serial_sequence('public.clients', 'ref'),  (select max(ref) from public.clients));",
  );
  w(
    "  perform setval(pg_get_serial_sequence('public.pets', 'ref'),     (select max(ref) from public.pets));",
  );
  w(
    "  perform setval(pg_get_serial_sequence('public.bookings', 'ref'), (select max(ref) from public.bookings));",
  );
});

w("select");
w("  (select count(*) from public.clients)      as clients,");
w("  (select count(*) from public.pets)         as pets,");
w("  (select count(*) from public.bookings)     as bookings,");
w("  (select count(*) from public.booking_pets) as booking_pets;");

mkdirSync(join("supabase", "seed"), { recursive: true });
writeFileSync(
  join("supabase", "seed", "facility-11-data.sql"),
  out.join("\n") + "\n",
);

console.log(`clients:  ${rows.clients.length}`);
console.log(`pets:     ${rows.pets.length}`);
console.log(`staff:    ${rows.staff.length}`);
console.log(
  `bookings: ${rows.bookings.length}${rows.skippedBookings ? ` (${rows.skippedBookings} skipped — unknown client)` : ""}`,
);
reportAnomalies(rows);
console.log(`\nwrote supabase/seed/facility-11-data.sql`);
