-- ============================================================================
-- Clients, pets and bookings — the operational core.
--
-- Until now Postgres held tenancy and identity only: orgs, facilities,
-- locations, profiles, memberships, permissions. Customers did not exist as
-- rows, which is why a real signup produced a real account attached to
-- nothing, and why two "bridge" files exist in src/lib/auth to paper over it.
-- This is the schema that lets both be deleted.
--
-- ── Shape: columns for what we query, jsonb for the long tail ───────────────
-- The mock Booking type has ~60 fields — grooming stages, feeding schedules,
-- medication instructions, invoice line items, belongings, evaluation state.
-- Modelling every one as a column would mean a migration per product tweak and
-- a table nobody can read. Modelling ALL of it as jsonb would mean no index
-- can ever help.
--
-- So: anything used to find, filter, sort, join or authorise a row is a
-- column. Everything else lives in `details`, and the API layer reassembles
-- the original object by spreading details and overlaying the columns. That
-- keeps the TypeScript shape byte-identical to today's mocks, which is what
-- lets the swap happen without touching 200 components.
--
-- ── `ref`: why there are two ids ────────────────────────────────────────────
-- `id` is a uuid, like every other table here. `ref` is the app-facing NUMBER,
-- because Booking.id / Client.id / Pet.id are `number` throughout the
-- TypeScript and in URLs users have bookmarked. An identity column preserves
-- those exact values for seeded rows and keeps issuing new ones afterwards.
-- Dropping `ref` is the follow-up once the front end speaks uuids.
--
-- ── Customers can read their own records ────────────────────────────────────
-- clients.profile_id links a client record to an auth account. It is what
-- makes the customer portal real rather than a view onto mock arrays, and the
-- RLS below is written so a signed-in pet owner sees their own client row,
-- their own pets and their own bookings — and nothing else in the facility.
-- ============================================================================

-- ── Enums ───────────────────────────────────────────────────────────────────
-- Mirrors bookingStatusEnum in src/types/base.ts. Kept in the same order as
-- the TypeScript so a diff between the two is readable.
create type public.booking_status as enum (
  'pending',
  'estimate_sent',
  'request_submitted',
  'waitlisted',
  'confirmed',
  'checked_in',
  'in_progress',
  'ready',
  'completed',
  'no_show',
  'cancelled',
  'declined'
);

-- ── Clients ─────────────────────────────────────────────────────────────────

create table public.clients (
  id           uuid primary key default gen_random_uuid(),
  ref          bigint generated by default as identity unique,
  facility_id  uuid not null references public.facilities (id) on delete cascade,

  -- The auth account, once the customer has one. Null for records a facility
  -- created on the client's behalf — which is most of them, and stays valid:
  -- a client is a relationship with a business, not a login.
  profile_id   uuid references public.profiles (id) on delete set null,

  name         text not null,
  email        text not null,
  phone        text,
  status       text not null default 'active',
  preferred_language text,
  image_url    text,
  address      jsonb,

  is_blocked     boolean not null default false,
  blocked_at     timestamptz,
  blocked_reason text,

  -- Denormalised because every client list sorts or filters on them.
  last_visit_date     date,
  outstanding_balance numeric(12,2) not null default 0,
  no_show_count       integer not null default 0,

  -- membership, packages, storeCredit, savedCards, customerSettings,
  -- additionalContacts — displayed on the profile, never queried across rows.
  details      jsonb not null default '{}'::jsonb,

  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),

  -- One client record per email per facility. Scoped to the facility, not
  -- global: the same person really can be a customer of two businesses on the
  -- platform, and they are two relationships.
  constraint clients_facility_email_key unique (facility_id, email)
);

comment on column public.clients.ref is
  'App-facing numeric id, matching Client.id in TypeScript. Drop once the front end uses uuids.';
comment on column public.clients.profile_id is
  'The customer''s auth account, when they have signed up. Null is normal.';

create index clients_facility_idx on public.clients (facility_id);
create index clients_profile_idx  on public.clients (profile_id) where profile_id is not null;
create index clients_name_idx     on public.clients (facility_id, lower(name));

-- ── Pets ────────────────────────────────────────────────────────────────────

create table public.pets (
  id           uuid primary key default gen_random_uuid(),
  ref          bigint generated by default as identity unique,
  client_id    uuid not null references public.clients (id) on delete cascade,

  -- Denormalised from the owner so every policy and facility-wide query on
  -- pets avoids a join back through clients. Kept honest by the trigger below.
  facility_id  uuid not null references public.facilities (id) on delete cascade,

  name         text not null,
  species      text not null default 'dog',   -- `type` in the TypeScript
  breed        text,
  age_years    integer,
  date_of_birth date,
  weight       numeric(6,2),
  color        text,
  microchip    text,
  allergies    text,
  special_needs text,
  sex          text check (sex is null or sex in ('male', 'female')),
  spayed_neutered boolean,
  coat_type    text check (coat_type is null or coat_type in ('short','medium','long','wire','curly','hairless')),
  energy_level text check (energy_level is null or energy_level in ('low','medium','high')),
  status       text not null default 'active'
                 check (status in ('active','inactive','deceased')),
  image_url    text,

  -- evaluations, visitPhotos
  details      jsonb not null default '{}'::jsonb,

  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index pets_client_idx   on public.pets (client_id);
create index pets_facility_idx on public.pets (facility_id);

-- A pet's facility must be its owner's. Enforced rather than trusted: a
-- mismatch would make the pet invisible to its own facility's staff while
-- remaining visible to another's, which is the worst kind of RLS bug — silent,
-- and wrong in the permissive direction.
create or replace function private.pets_inherit_facility()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  select c.facility_id into new.facility_id
    from public.clients c where c.id = new.client_id;
  return new;
end;
$$;

create trigger pets_set_facility
  before insert or update of client_id on public.pets
  for each row execute function private.pets_inherit_facility();

-- ── Bookings ────────────────────────────────────────────────────────────────

create table public.bookings (
  id           uuid primary key default gen_random_uuid(),
  ref          bigint generated by default as identity unique,
  facility_id  uuid not null references public.facilities (id) on delete cascade,
  location_id  uuid references public.locations (id) on delete set null,
  client_id    uuid not null references public.clients (id) on delete cascade,

  service      text not null,
  service_type text,
  status       public.booking_status not null default 'pending',
  payment_status text not null default 'pending'
                 check (payment_status in ('pending','paid','refunded')),

  -- Timestamps, not the mock's separate date + "14:00" strings. A booking that
  -- runs overnight or crosses a DST boundary cannot be reasoned about as a
  -- date plus a wall-clock string, and every calendar query wants a range.
  start_at     timestamptz not null,
  end_at       timestamptz not null,

  -- The membership, not the profile: someone can be staff at two facilities
  -- and only one of those assignments is relevant to this booking.
  assigned_staff_id uuid references public.facility_memberships (id) on delete set null,
  -- The mock's display-name string, kept until every booking has a real
  -- assignment. src/lib/api/booking.ts currently INVENTS this by rotating
  -- bookings across a staff pool; that becomes dead code for real rows.
  assigned_staff_name text,

  base_price   numeric(12,2) not null default 0,
  discount     numeric(12,2) not null default 0,
  total_cost   numeric(12,2) not null default 0,
  tip_amount   numeric(12,2),

  special_requests text,

  -- feedingSchedule, medications, groomingStages, invoice, belongings,
  -- daycareSelectedDates, evaluation state, kennel/unit assignment …
  details      jsonb not null default '{}'::jsonb,

  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),

  constraint bookings_ends_after_start check (end_at >= start_at)
);

create index bookings_facility_start_idx on public.bookings (facility_id, start_at desc);
create index bookings_client_idx         on public.bookings (client_id);
create index bookings_staff_idx          on public.bookings (assigned_staff_id)
  where assigned_staff_id is not null;
create index bookings_status_idx         on public.bookings (facility_id, status);

-- A booking can cover several pets (the mock's `petId: number | number[]`),
-- so this is a join table rather than a column.
create table public.booking_pets (
  booking_id uuid not null references public.bookings (id) on delete cascade,
  pet_id     uuid not null references public.pets (id) on delete cascade,
  primary key (booking_id, pet_id)
);

create index booking_pets_pet_idx on public.booking_pets (pet_id);

-- ── updated_at ──────────────────────────────────────────────────────────────

create trigger clients_set_updated_at
  before update on public.clients
  for each row execute function private.set_updated_at();

create trigger pets_set_updated_at
  before update on public.pets
  for each row execute function private.set_updated_at();

create trigger bookings_set_updated_at
  before update on public.bookings
  for each row execute function private.set_updated_at();

-- ── Who is the caller, as a customer? ───────────────────────────────────────
-- SECURITY DEFINER so it can read clients while clients' own policies are
-- being evaluated, and in `private` so it is not exposed as an RPC — a
-- client-callable function that returns ids is a discovery tool.
create or replace function private.own_client_ids()
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select c.id from public.clients c where c.profile_id = (select auth.uid());
$$;

-- `authenticated` must be granted EXPLICITLY. Revoking from PUBLIC also
-- removes what authenticated inherits through it, and every policy calling
-- this then fails with "permission denied for function own_client_ids" — which
-- surfaces as a customer being unable to read their own pets. What keeps the
-- function away from clients is that `private` is not an exposed PostgREST
-- schema, not the absence of a grant.
grant execute on function private.own_client_ids() to authenticated;
revoke execute on function private.own_client_ids() from anon;

-- ── RLS ─────────────────────────────────────────────────────────────────────
-- Two audiences per table, and they are not symmetrical:
--   staff     — permission-gated, scoped to facilities they belong to
--   customers — their own records only, no permission needed
--
-- auth.uid() is wrapped in (select …) so Postgres evaluates it once per query
-- rather than once per row (the auth_rls_initplan advisory).
-- Writes are split into insert/update/delete rather than `for all`, so a
-- read-only grant cannot accidentally carry write rights.

alter table public.clients      enable row level security;
alter table public.pets         enable row level security;
alter table public.bookings     enable row level security;
alter table public.booking_pets enable row level security;

-- Clients
create policy clients_read on public.clients
  for select to authenticated
  using (
    private.is_platform_admin()
    or profile_id = (select auth.uid())
    or private.has_permission(facility_id, 'view_clients')
  );

create policy clients_insert on public.clients
  for insert to authenticated
  with check (private.has_permission(facility_id, 'create_clients'));

create policy clients_update on public.clients
  for update to authenticated
  using (
    profile_id = (select auth.uid())
    or private.has_permission(facility_id, 'edit_clients')
  )
  with check (
    profile_id = (select auth.uid())
    or private.has_permission(facility_id, 'edit_clients')
  );

create policy clients_delete on public.clients
  for delete to authenticated
  using (private.has_permission(facility_id, 'delete_clients'));

-- Pets
create policy pets_read on public.pets
  for select to authenticated
  using (
    private.is_platform_admin()
    or client_id in (select private.own_client_ids())
    or private.has_permission(facility_id, 'view_pet_records')
  );

create policy pets_insert on public.pets
  for insert to authenticated
  with check (
    client_id in (select private.own_client_ids())
    or private.has_permission(facility_id, 'edit_pet_records')
  );

create policy pets_update on public.pets
  for update to authenticated
  using (
    client_id in (select private.own_client_ids())
    or private.has_permission(facility_id, 'edit_pet_records')
  )
  with check (
    client_id in (select private.own_client_ids())
    or private.has_permission(facility_id, 'edit_pet_records')
  );

create policy pets_delete on public.pets
  for delete to authenticated
  using (private.has_permission(facility_id, 'edit_pet_records'));

-- Bookings
create policy bookings_read on public.bookings
  for select to authenticated
  using (
    private.is_platform_admin()
    or client_id in (select private.own_client_ids())
    or private.has_permission(facility_id, 'view_bookings')
  );

-- A customer booking for themselves is a real path, so the check is "is this
-- your own client record" OR the staff permission — not staff-only.
create policy bookings_insert on public.bookings
  for insert to authenticated
  with check (
    client_id in (select private.own_client_ids())
    or private.has_permission(facility_id, 'create_bookings')
  );

create policy bookings_update on public.bookings
  for update to authenticated
  using (private.has_permission(facility_id, 'edit_bookings'))
  with check (private.has_permission(facility_id, 'edit_bookings'));

-- No delete policy, deliberately: bookings are cancelled, not deleted. Status
-- carries that, and the financial and no-show history has to survive it.

-- Booking ↔ pets: inherits the booking's visibility rather than restating it,
-- so the two can never disagree.
create policy booking_pets_read on public.booking_pets
  for select to authenticated
  using (exists (select 1 from public.bookings b where b.id = booking_id));

create policy booking_pets_insert on public.booking_pets
  for insert to authenticated
  with check (exists (select 1 from public.bookings b where b.id = booking_id));

create policy booking_pets_delete on public.booking_pets
  for delete to authenticated
  using (exists (select 1 from public.bookings b where b.id = booking_id));

-- Caught by the performance advisor after the fact: without this, deleting or
-- re-pointing a location sequentially scans every booking.
create index bookings_location_idx on public.bookings (location_id)
  where location_id is not null;
