-- ============================================================================
-- A ref supplied by hand must carry the sequence with it.
--
-- ── THE BUG, FOUND BY rooms-admin.spec.ts ON 2026-08-20 ───────────────────
--
--   POST /api/bookings -> 500
--   duplicate key value violates unique constraint "bookings_ref_key"
--
-- `bookings.ref` is `bigint generated BY DEFAULT as identity`. BY DEFAULT means
-- an INSERT may supply its own value — and when it does, Postgres does NOT
-- advance the sequence. Seeds do exactly that, because the fixtures reference
-- booking 896 by number and those refs have to be stable.
--
-- So every hand-numbered row widens a gap:
--
--   max(ref) = 1018    bookings_ref_seq.last_value = 1017
--
-- The next booking anyone created drew 1018, collided, and got a 500. That was
-- the live state of production when this was written.
--
-- ── IT LOOKS INTERMITTENT, WHICH IS WHY IT SURVIVED ───────────────────────
--
-- `nextval` is non-transactional: the failed insert still burns the number. So
-- the first attempt 500s, the operator presses the button again, the second
-- draws 1019 and works. It reads as a glitch rather than a bug — and it comes
-- back the moment anything inserts an explicit ref again.
--
-- ── WHY NOT `GENERATED ALWAYS` ────────────────────────────────────────────
--
-- That is the usual advice and it is wrong here. ALWAYS refuses a supplied
-- value outright, so every seed would need OVERRIDING SYSTEM VALUE — and any
-- that was missed would fail loudly at seed time rather than quietly here.
-- The refs need to stay assignable; what they must stop doing is leaving the
-- sequence behind.
--
-- ── STATEMENT-LEVEL, WITH A TRANSITION TABLE ──────────────────────────────
--
-- Per-row would call setval 202 times seeding 202 bookings. A statement-level
-- trigger with `referencing new table as inserted` syncs once per statement and
-- sees every row, which is the same answer for a fraction of the work.
--
-- Every trigger below must name the transition table `inserted`, because the
-- function reads it by that name.
-- ============================================================================

create or replace function private.ref_sequence_follows_explicit_values()
returns trigger
language plpgsql
security definer
set search_path = ''
as $fn$
declare
  v_seq  text;
  v_max  bigint;
  v_last bigint;
begin
  select max(ref) into v_max from inserted;
  if v_max is null then
    return null;
  end if;

  v_seq := pg_catalog.pg_get_serial_sequence(
    tg_table_schema || '.' || tg_table_name, 'ref');
  if v_seq is null then
    return null;
  end if;

  execute format('select last_value from %s', v_seq) into v_last;

  -- Only ever FORWARD. `greatest` rather than a bare setval so a concurrent
  -- nextval that has already moved past us is not dragged back — pulling the
  -- sequence backwards would manufacture the very collision this prevents.
  if v_max > v_last then
    perform setval(v_seq, greatest(v_max, v_last), true);
  end if;

  return null;
end;
$fn$;

comment on function private.ref_sequence_follows_explicit_values() is
  'Advance a table''s `ref` identity sequence past any explicitly supplied value. Statement-level; the trigger must declare `referencing new table as inserted`.';

drop trigger if exists bookings_ref_sequence_follows on public.bookings;
create trigger bookings_ref_sequence_follows
  after insert on public.bookings
  referencing new table as inserted
  for each statement
  execute function private.ref_sequence_follows_explicit_values();

drop trigger if exists clients_ref_sequence_follows on public.clients;
create trigger clients_ref_sequence_follows
  after insert on public.clients
  referencing new table as inserted
  for each statement
  execute function private.ref_sequence_follows_explicit_values();

drop trigger if exists pets_ref_sequence_follows on public.pets;
create trigger pets_ref_sequence_follows
  after insert on public.pets
  referencing new table as inserted
  for each statement
  execute function private.ref_sequence_follows_explicit_values();

-- ── And repair the drift that is already there ────────────────────────────
--
-- The trigger only fires on future inserts, so the three sequences standing
-- behind their tables today would still hand out one collision each. Done as
-- a DO block over the same three tables rather than three hand-written
-- setvals, so it cannot disagree with the list above.

do $repair$
declare
  v_table text;
  v_seq   text;
  v_max   bigint;
  v_last  bigint;
begin
  foreach v_table in array array['bookings', 'clients', 'pets'] loop
    v_seq := pg_catalog.pg_get_serial_sequence('public.' || v_table, 'ref');
    continue when v_seq is null;

    execute format('select max(ref) from public.%I', v_table) into v_max;
    execute format('select last_value from %s', v_seq) into v_last;

    if v_max is not null and v_max > v_last then
      perform setval(v_seq, v_max, true);
      raise notice 'public.% ref sequence moved % -> %', v_table, v_last, v_max;
    end if;
  end loop;
end;
$repair$;
