-- ============================================================================
-- An incident is a row, and a bad review can point at one.
--
-- -- WHY THIS EXISTS NOW ----------------------------------------------------
--
-- `review_escalations` deliberately shipped WITHOUT an `incident_id`, because
-- there were no incidents to point at: src/data/incidents.ts is 651 lines of
-- fixtures and `log_incidents`, `ops_incidents_view` and `ops_incidents_manage`
-- are permission keys with nothing behind them. A nullable FK to a table that
-- does not exist is a claim the schema cannot keep -- which is exactly how
-- `facility_tasks.source = 'reputation_escalation'` came to sit reserved and
-- unused for months.
--
-- So the column arrives in the same migration as the table, as promised.
--
-- -- WHAT THIS DOES AND DOES NOT CONVERT ------------------------------------
--
-- The RECORD is real: what happened, to which pets, how bad, who reported it,
-- and the two sets of notes a facility keeps (one for staff, one the owner may
-- read). That is what an escalation needs to point at and what a manager needs
-- to answer a complaint.
--
-- NOT converted, and still fixtures: incident photos, follow-up tasks, care
-- actions, medications, billing and owner notifications. Each is its own table
-- and its own screen. Converting the record without them is honest -- the
-- incident module continues to work exactly as it did -- whereas adding six
-- empty tables to look finished is the shape this file exists to avoid.
--
-- -- THE TWO SETS OF NOTES ARE NOT A STYLE CHOICE ---------------------------
--
-- `internal_notes` is what staff write for each other; `client_notes` is what
-- the owner is told. Keeping them in one column and trusting a screen to redact
-- is how the wrong half reaches a customer -- and this is the table a manager
-- opens WHILE ON THE PHONE to somebody whose dog was hurt.
-- ============================================================================

create table if not exists public.incidents (
  id uuid primary key default gen_random_uuid(),
  ref bigint generated by default as identity unique,

  facility_id uuid not null references public.facilities(id) on delete cascade,
  location_id uuid references public.locations(id) on delete set null,
  booking_id  uuid references public.bookings(id) on delete set null,
  client_id   uuid references public.clients(id) on delete set null,

  kind text not null check (kind in (
    'injury', 'illness', 'behavioral', 'accident', 'escape', 'fight', 'other')),
  severity text not null check (severity in ('low', 'medium', 'high', 'critical')),
  status text not null default 'open'
    check (status in ('open', 'investigating', 'resolved', 'closed')),

  title text not null check (btrim(title) <> ''),
  description text not null default '',

  -- See the header. Two columns, on purpose.
  internal_notes text not null default '',
  client_notes   text not null default '',

  pet_ids   uuid[] not null default '{}',
  staff_ids uuid[] not null default '{}',

  occurred_at timestamptz not null,
  reported_at timestamptz not null default now(),
  reported_by text references public.profiles(id) on delete set null,
  resolved_at timestamptz,
  resolved_by text references public.profiles(id) on delete set null,

  -- Whether the owner has been told. A separate fact from `status`: an incident
  -- can be resolved and the owner still not know, which is the failure the
  -- 1-star review in the audit was actually about.
  owner_notified_at timestamptz,
  owner_notified_by text references public.profiles(id) on delete set null,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint incidents_resolved_says_when
    check ((status in ('resolved', 'closed')) = (resolved_at is not null)),
  constraint incidents_reported_after_it_happened
    check (reported_at >= occurred_at - interval '1 day')
);

create index if not exists incidents_facility_idx
  on public.incidents (facility_id, occurred_at desc);
create index if not exists incidents_open_idx
  on public.incidents (facility_id, severity)
  where status in ('open', 'investigating');
create index if not exists incidents_client_idx
  on public.incidents (client_id, occurred_at desc)
  where client_id is not null;

comment on table public.incidents is
  'What happened to an animal in our care. internal_notes and client_notes are separate columns so the wrong half cannot reach an owner.';
comment on column public.incidents.owner_notified_at is
  'Whether the owner has been TOLD - a different fact from status. An incident can be resolved with the owner still unaware.';

-- -- The link a bad review can finally make ---------------------------------
--
-- The spec's case: a 1-star daycare review reading "Nala had a cut on her leg
-- when I picked her up and staff didn't mention it." The Protection Rules
-- already knew how to block a review request when a booking has a critical
-- incident -- and nothing could create the incident, so the rule guarded a
-- condition that could never be true. This closes that loop in the direction
-- it was always missing.

alter table public.review_escalations
  add column if not exists incident_id uuid
    references public.incidents(id) on delete set null;

comment on column public.review_escalations.incident_id is
  'The incident this complaint turned out to be about, if any. Nullable and set by a person: an escalation is not evidence that something happened, it is evidence somebody is unhappy.';

-- -- RLS --------------------------------------------------------------------
--
-- The permission keys have existed in seed.sql since the beginning with nothing
-- enforcing them. They enforce something now.

alter table public.incidents enable row level security;

drop policy if exists incidents_read on public.incidents;
create policy incidents_read on public.incidents
  for select using (
    private.is_platform_admin()
    or private.has_permission(facility_id, 'ops_incidents_view')
    -- The owner may read their own, and ONLY the columns a client should see is
    -- not something RLS can express -- so the customer-facing route selects a
    -- narrow list and `internal_notes` is never in it. See the API route.
    or client_id in (select private.own_client_ids())
  );

-- Reporting one is a care act, not a management act: the person who saw it
-- happen must be able to write it down immediately.
drop policy if exists incidents_insert on public.incidents;
create policy incidents_insert on public.incidents
  for insert with check (private.has_permission(facility_id, 'log_incidents'));

-- Editing one afterwards is a management act. The distinction matters: a
-- caretaker records what they saw; changing severity or closing it is somebody
-- accountable for the answer.
drop policy if exists incidents_update on public.incidents;
create policy incidents_update on public.incidents
  for update using (private.has_permission(facility_id, 'ops_incidents_manage'))
          with check (private.has_permission(facility_id, 'ops_incidents_manage'));

-- NO DELETE POLICY, for anybody. An incident is the record that something
-- happened to an animal in this facility's care, and it is the first thing a
-- facility would want gone after a bad outcome. Correct it, close it, but it
-- does not disappear.

revoke all on public.incidents from public, anon;
grant select, insert, update on public.incidents to authenticated;

-- EXPLICIT, because Supabase default privileges hand `authenticated` the full
-- set on every new table in `public` and not granting is not removing.
revoke delete on public.incidents from authenticated;

grant select, insert, update, delete on public.incidents to service_role;

do $verify$
begin
  if has_table_privilege('anon', 'public.incidents', 'select') then
    raise exception 'anon can read incidents';
  end if;
  if has_table_privilege('authenticated', 'public.incidents', 'delete') then
    raise exception 'an incident can be deleted';
  end if;
end;
$verify$;
